/**
 * FlashcardInfographic, PNG infographics generated by NotebookLM.
 * Each flashcard gets a tailored square infographic displayed below the text.
 * Finn illustrations appear on key thematic flashcards as character art.
 *
 * To enable a chapter: uncomment its require() lines after generating PNGs.
 * Generate with: bash scripts/generate_module_infographic.sh <module-id>
 */
import { useState, useCallback, useEffect, useRef } from "react";
import { View, Image, Text, StyleSheet, Pressable, Modal, Platform } from "react-native";
import Animated, { useSharedValue, useAnimatedStyle, withTiming, withRepeat, withSequence, Easing, interpolate, Extrapolation, useReducedMotion } from "react-native-reanimated";
import { Image as ExpoImage } from "expo-image";
import type { ImageSource, ImageLoadEventData } from "expo-image";
import type { ImageSourcePropType } from "react-native";
import LottieView from "lottie-react-native";
import type { AnimationObject } from "lottie-react-native";
import { captureEvent } from "../../lib/posthog";
import { toProxiedImageUri } from "../../lib/imageProxy";

const AnimatedExpoImage = Animated.createAnimatedComponent(ExpoImage);

/** Finn character illustrations, shown as full-screen transition between cards */
export const FINN_MAP: Record<string, ImageSourcePropType> = {
  // fc-0-3-2 removed, Finn transition not useful in inflation module
  "fc-1-3-2": { uri: 'https://8mnwcjygpqev3keg.public.blob.vercel-storage.com/infographics/finn-installments.png' },   // אשראי מתגלגל, כריש עם עוגן
  "fc-3-15-1": { uri: 'https://8mnwcjygpqev3keg.public.blob.vercel-storage.com/infographics/finn-inflation.png' },     // אינפלציה, תיבת אוצר נשחקת
  "fc-4-23-1": { uri: 'https://8mnwcjygpqev3keg.public.blob.vercel-storage.com/infographics/finn-passive.png' },       // דיבידנד, דגי זהב פסיביים
  "fc-5-25-1": { uri: 'https://8mnwcjygpqev3keg.public.blob.vercel-storage.com/infographics/finn-freedom.png' },       // FIRE, חופש כלכלי
};

/** Finn images shown as tappable portrait thumbnails, tap to open full-screen, tap to dismiss */
const FINN_TAP_MAP: Record<string, ImageSourcePropType> = {
};

const LOTTIE_MAP: Record<string, number> = {
  // מושגי יסוד פיננסיים (mod-0-2)
  "fc-0-2-1": require("../../../assets/lottie/wired-flat-413-money-bag-hover-shake.json"), // בנק
  "fc-0-2-2": require("../../../assets/lottie/wired-flat-1023-portfolio-hover-pinch.json"), // עו"ש
  "fc-0-2-3": require("../../../assets/lottie/wired-flat-161-growth-hover-pinch.json"), // ריבית
  "fc-0-2-4": require("../../../assets/lottie/wired-flat-983-smart-lock-card-hover-pinch.json"), // אשראי
  "fc-0-2-5": require("../../../assets/lottie/wired-flat-3051-pot-gold-hover-pinch.json"), // פנסיה
};

export const INFOGRAPHIC_MAP: Record<string, ImageSource | null> = {
  // ═══════════════════════════════════════════════════════════════
  // CHAPTER 0: המבוא
  // ═══════════════════════════════════════════════════════════════

  // Module 0-1: מה זה כסף
  "fc-0-1-1": { uri: 'https://8mnwcjygpqev3keg.public.blob.vercel-storage.com/infographics/mod-0-1/fc-0-1-1.png' },
  "fc-0-1-2": { uri: 'https://8mnwcjygpqev3keg.public.blob.vercel-storage.com/infographics/mod-0-1/fc-0-1-2.png' },
  "fc-0-1-3": { uri: 'https://8mnwcjygpqev3keg.public.blob.vercel-storage.com/infographics/mod-0-1/fc-0-1-3.png' },
  "fc-0-1-4": { uri: 'https://8mnwcjygpqev3keg.public.blob.vercel-storage.com/infographics/mod-0-1/fc-0-1-4.png' },
  "fc-0-1-5": { uri: 'https://8mnwcjygpqev3keg.public.blob.vercel-storage.com/infographics/mod-0-1/fc-0-1-5.png' },

  // Module 0-2: מושגי יסוד
  // ?v=2 cache-bust appended 2026-06-05 — PostHog showed dozens of cached
  // 303/403 failures on these specific URLs (iOS CFNetwork + Vercel Blob
  // throttling). Changing the cache key forces ExpoImage to drop the stale
  // failure state and re-fetch on next view, even before the retry logic
  // kicks in. Safe: the Blob ignores query strings, the PNG bytes are
  // unchanged.
  "fc-0-2-1": { uri: 'https://8mnwcjygpqev3keg.public.blob.vercel-storage.com/infographics/mod-0-2/fc-0-2-1.png?v=2' },
  "fc-0-2-2": { uri: 'https://8mnwcjygpqev3keg.public.blob.vercel-storage.com/infographics/mod-0-2/fc-0-2-2.png?v=2' },
  "fc-0-2-3": { uri: 'https://8mnwcjygpqev3keg.public.blob.vercel-storage.com/infographics/mod-0-2/fc-0-2-3.png?v=2' },
  "fc-0-2-4": { uri: 'https://8mnwcjygpqev3keg.public.blob.vercel-storage.com/infographics/mod-0-2/fc-0-2-4.png?v=2' },
  "fc-0-2-5": { uri: 'https://8mnwcjygpqev3keg.public.blob.vercel-storage.com/infographics/mod-0-2/fc-0-2-5.png?v=2' },
  // Module 0-3: אינפלציה
  "fc-0-3-1": { uri: 'https://8mnwcjygpqev3keg.public.blob.vercel-storage.com/infographics/mod-0-3/fc-0-3-1.png' },
  "fc-0-3-2": { uri: 'https://8mnwcjygpqev3keg.public.blob.vercel-storage.com/infographics/mod-0-3/fc-0-3-2.png' },
  "fc-0-3-3": { uri: 'https://8mnwcjygpqev3keg.public.blob.vercel-storage.com/infographics/mod-0-3/fc-0-3-3.png' },
  "fc-0-3-4": { uri: 'https://8mnwcjygpqev3keg.public.blob.vercel-storage.com/infographics/mod-0-3/fc-0-3-4.png' },
  "fc-0-3-5": { uri: 'https://8mnwcjygpqev3keg.public.blob.vercel-storage.com/infographics/mod-0-3/fc-0-3-5.png' },
  // Module 0-4: הכנסות והוצאות
  "fc-0-4-1": { uri: 'https://8mnwcjygpqev3keg.public.blob.vercel-storage.com/infographics/mod-0-4/fc-0-4-1.png' },
  "fc-0-4-2": { uri: 'https://8mnwcjygpqev3keg.public.blob.vercel-storage.com/infographics/mod-0-4/fc-0-4-2.png' },
  "fc-0-4-3": { uri: 'https://8mnwcjygpqev3keg.public.blob.vercel-storage.com/infographics/mod-0-4/fc-0-4-3.png' },
  "fc-0-4-4": { uri: 'https://8mnwcjygpqev3keg.public.blob.vercel-storage.com/infographics/mod-0-4/fc-0-4-4.png' },
  // Module 0-5: למה להשקיע
  "fc-0-5-1": { uri: 'https://8mnwcjygpqev3keg.public.blob.vercel-storage.com/infographics/mod-0-5/fc-0-5-1.png' },
  "fc-0-5-2": { uri: 'https://8mnwcjygpqev3keg.public.blob.vercel-storage.com/infographics/mod-0-5/fc-0-5-2.png' },
  "fc-0-5-3": { uri: 'https://8mnwcjygpqev3keg.public.blob.vercel-storage.com/infographics/mod-0-5/fc-0-5-3.png' },
  "fc-0-5-4": { uri: 'https://8mnwcjygpqev3keg.public.blob.vercel-storage.com/infographics/mod-0-5/fc-0-5-4.png' },

  // ═══════════════════════════════════════════════════════════════
  // CHAPTER 1: יסודות
  // ═══════════════════════════════════════════════════════════════

  // Module 1-1: תזרים ותקציב
  "fc-1-1-1": { uri: 'https://8mnwcjygpqev3keg.public.blob.vercel-storage.com/infographics/mod-1-1/fc-1-1-1.png' },
  "fc-1-1-2": { uri: 'https://8mnwcjygpqev3keg.public.blob.vercel-storage.com/infographics/mod-1-1/fc-1-1-2.png' },
  "fc-1-1-3": { uri: 'https://8mnwcjygpqev3keg.public.blob.vercel-storage.com/infographics/mod-1-1/fc-1-1-3.png' },
  "fc-1-1-4": { uri: 'https://8mnwcjygpqev3keg.public.blob.vercel-storage.com/infographics/mod-1-1/fc-1-1-4.png' },
  "fc-1-1-5": { uri: 'https://8mnwcjygpqev3keg.public.blob.vercel-storage.com/infographics/mod-1-1/fc-1-1-5.png' },
  "fc-1-1-6": { uri: 'https://8mnwcjygpqev3keg.public.blob.vercel-storage.com/infographics/mod-1-1/fc-1-1-6.png' },
  // Module 1-2: מלכודת המינוס
  "fc-1-2-1": { uri: 'https://8mnwcjygpqev3keg.public.blob.vercel-storage.com/infographics/mod-1-2/fc-1-2-1.png' },
  "fc-1-2-2": { uri: 'https://8mnwcjygpqev3keg.public.blob.vercel-storage.com/infographics/mod-1-2/fc-1-2-2.png' },
  "fc-1-2-3": { uri: 'https://8mnwcjygpqev3keg.public.blob.vercel-storage.com/infographics/mod-1-2/fc-1-2-3.png' },
  "fc-1-2-4": { uri: 'https://8mnwcjygpqev3keg.public.blob.vercel-storage.com/infographics/mod-1-2/fc-1-2-4.png' },
  "fc-1-2-5": { uri: 'https://8mnwcjygpqev3keg.public.blob.vercel-storage.com/infographics/mod-1-2/fc-1-2-5.png' },
  "fc-1-2-6": { uri: 'https://8mnwcjygpqev3keg.public.blob.vercel-storage.com/infographics/mod-1-2/fc-1-2-6.png' },
  // Module 1-3: אשראי
  "fc-1-3-1": { uri: 'https://8mnwcjygpqev3keg.public.blob.vercel-storage.com/infographics/mod-1-3/fc-1-3-1.png' },
  "fc-1-3-2": { uri: 'https://8mnwcjygpqev3keg.public.blob.vercel-storage.com/infographics/mod-1-3/fc-1-3-2.png' },
  "fc-1-3-3": { uri: 'https://8mnwcjygpqev3keg.public.blob.vercel-storage.com/infographics/mod-1-3/fc-1-3-3.png' },
  "fc-1-3-4": { uri: 'https://8mnwcjygpqev3keg.public.blob.vercel-storage.com/infographics/mod-1-3/fc-1-3-4.png' },
  "fc-1-3-5": { uri: 'https://8mnwcjygpqev3keg.public.blob.vercel-storage.com/infographics/mod-1-3/fc-1-3-5.png' },
  "fc-1-3-6": { uri: 'https://8mnwcjygpqev3keg.public.blob.vercel-storage.com/infographics/mod-1-3/fc-1-3-6.png' },
  // Module 1-4: ריבית דריבית
  "fc-1-4-1": { uri: 'https://8mnwcjygpqev3keg.public.blob.vercel-storage.com/infographics/mod-1-4/fc-1-4-1.png' },
  "fc-1-4-2": { uri: 'https://8mnwcjygpqev3keg.public.blob.vercel-storage.com/infographics/mod-1-4/fc-1-4-2.png' },
  "fc-1-4-3": { uri: 'https://8mnwcjygpqev3keg.public.blob.vercel-storage.com/infographics/mod-1-4/fc-1-4-3.png' },
  "fc-1-4-4": { uri: 'https://8mnwcjygpqev3keg.public.blob.vercel-storage.com/infographics/mod-1-4/fc-1-4-4.png' },
  "fc-1-4-5": { uri: 'https://8mnwcjygpqev3keg.public.blob.vercel-storage.com/infographics/mod-1-4/fc-1-4-5.png' },
  "fc-1-4-6": { uri: 'https://8mnwcjygpqev3keg.public.blob.vercel-storage.com/infographics/mod-1-4/fc-1-4-6.png' },
  // Module 1-5: לקרוא תלוש שכר
  "fc-1-5-1": { uri: 'https://8mnwcjygpqev3keg.public.blob.vercel-storage.com/infographics/mod-1-5/fc-1-5-1.png' },
  "fc-1-5-2": { uri: 'https://8mnwcjygpqev3keg.public.blob.vercel-storage.com/infographics/mod-1-5/fc-1-5-2.png' },
  "fc-1-5-3": { uri: 'https://8mnwcjygpqev3keg.public.blob.vercel-storage.com/infographics/mod-1-5/fc-1-5-3.png' },
  "fc-1-5-4": { uri: 'https://8mnwcjygpqev3keg.public.blob.vercel-storage.com/infographics/mod-1-5/fc-1-5-4.png' },
  "fc-1-5-5": { uri: 'https://8mnwcjygpqev3keg.public.blob.vercel-storage.com/infographics/mod-1-5/fc-1-5-5.png' },
  "fc-1-5-6": { uri: 'https://8mnwcjygpqev3keg.public.blob.vercel-storage.com/infographics/mod-1-5/fc-1-5-6.png' },
  // Module 1-6: הלוואות צרכניות
  "fc-1-6-1": { uri: 'https://8mnwcjygpqev3keg.public.blob.vercel-storage.com/infographics/mod-1-6/fc-1-6-1.png' },
  "fc-1-6-2": { uri: 'https://8mnwcjygpqev3keg.public.blob.vercel-storage.com/infographics/mod-1-6/fc-1-6-2.png' },
  "fc-1-6-3": { uri: 'https://8mnwcjygpqev3keg.public.blob.vercel-storage.com/infographics/mod-1-6/fc-1-6-3.png' },
  "fc-1-6-4": { uri: 'https://8mnwcjygpqev3keg.public.blob.vercel-storage.com/infographics/mod-1-6/fc-1-6-4.png' },
  "fc-1-6-5": { uri: 'https://8mnwcjygpqev3keg.public.blob.vercel-storage.com/infographics/mod-1-6/fc-1-6-5.png' },
  "fc-1-6-6": { uri: 'https://8mnwcjygpqev3keg.public.blob.vercel-storage.com/infographics/mod-1-6/fc-1-6-6.png' },
  // Module 1-7: חיסכון
  "fc-1-7-1": { uri: 'https://8mnwcjygpqev3keg.public.blob.vercel-storage.com/infographics/mod-1-7/fc-1-7-1.png' },
  "fc-1-7-2": { uri: 'https://8mnwcjygpqev3keg.public.blob.vercel-storage.com/infographics/mod-1-7/fc-1-7-2.png' },
  "fc-1-7-3": { uri: 'https://8mnwcjygpqev3keg.public.blob.vercel-storage.com/infographics/mod-1-7/fc-1-7-3.png' },
  "fc-1-7-4": { uri: 'https://8mnwcjygpqev3keg.public.blob.vercel-storage.com/infographics/mod-1-7/fc-1-7-4.png' },
  "fc-1-7-5": { uri: 'https://8mnwcjygpqev3keg.public.blob.vercel-storage.com/infographics/mod-1-7/fc-1-7-5.png' },
  "fc-1-7-6": { uri: 'https://8mnwcjygpqev3keg.public.blob.vercel-storage.com/infographics/mod-1-7/fc-1-7-6.png' },
  // Module 1-8: תכנון פיננסי
  "fc-1-8-1": { uri: 'https://8mnwcjygpqev3keg.public.blob.vercel-storage.com/infographics/mod-1-8/fc-1-8-1.png' },
  "fc-1-8-2": { uri: 'https://8mnwcjygpqev3keg.public.blob.vercel-storage.com/infographics/mod-1-8/fc-1-8-2.png' },
  "fc-1-8-3": { uri: 'https://8mnwcjygpqev3keg.public.blob.vercel-storage.com/infographics/mod-1-8/fc-1-8-3.png' },
  "fc-1-8-4": { uri: 'https://8mnwcjygpqev3keg.public.blob.vercel-storage.com/infographics/mod-1-8/fc-1-8-4.png' },
  "fc-1-8-5": { uri: 'https://8mnwcjygpqev3keg.public.blob.vercel-storage.com/infographics/mod-1-8/fc-1-8-5.png' },
  "fc-1-8-6": { uri: 'https://8mnwcjygpqev3keg.public.blob.vercel-storage.com/infographics/mod-1-8/fc-1-8-6.png' },
  // Module 1-9: הרגלי צריכה
  "fc-1-9-1": { uri: 'https://8mnwcjygpqev3keg.public.blob.vercel-storage.com/infographics/mod-1-9/fc-1-9-1.png' },
  "fc-1-9-2": { uri: 'https://8mnwcjygpqev3keg.public.blob.vercel-storage.com/infographics/mod-1-9/fc-1-9-2.png' },
  "fc-1-9-3": { uri: 'https://8mnwcjygpqev3keg.public.blob.vercel-storage.com/infographics/mod-1-9/fc-1-9-3.png' },
  "fc-1-9-4": { uri: 'https://8mnwcjygpqev3keg.public.blob.vercel-storage.com/infographics/mod-1-9/fc-1-9-4.png' },
  "fc-1-9-5": { uri: 'https://8mnwcjygpqev3keg.public.blob.vercel-storage.com/infographics/mod-1-9/fc-1-9-5.png' },
  "fc-1-9-6": { uri: 'https://8mnwcjygpqev3keg.public.blob.vercel-storage.com/infographics/mod-1-9/fc-1-9-6.png' },

  // ═══════════════════════════════════════════════════════════════
  // CHAPTER 2: ביטחון, uncomment after generating PNGs
  // ═══════════════════════════════════════════════════════════════

  // Module 2-10: דירוג אשראי
  "fc-2-10-1": { uri: 'https://8mnwcjygpqev3keg.public.blob.vercel-storage.com/infographics/mod-2-10/fc-2-10-1.png' },
  "fc-2-10-2": { uri: 'https://8mnwcjygpqev3keg.public.blob.vercel-storage.com/infographics/mod-2-10/fc-2-10-2.png' },
  "fc-2-10-3": { uri: 'https://8mnwcjygpqev3keg.public.blob.vercel-storage.com/infographics/mod-2-10/fc-2-10-3.png' },
  "fc-2-10-4": { uri: 'https://8mnwcjygpqev3keg.public.blob.vercel-storage.com/infographics/mod-2-10/fc-2-10-4.png' },
  "fc-2-10-5": { uri: 'https://8mnwcjygpqev3keg.public.blob.vercel-storage.com/infographics/mod-2-10/fc-2-10-5.png' },
  "fc-2-10-6": { uri: 'https://8mnwcjygpqev3keg.public.blob.vercel-storage.com/infographics/mod-2-10/fc-2-10-6.png' },
  // Module 2-11: נקודות זיכוי
  "fc-2-11-1": { uri: 'https://8mnwcjygpqev3keg.public.blob.vercel-storage.com/infographics/mod-2-11/fc-2-11-1.png' },
  "fc-2-11-2": { uri: 'https://8mnwcjygpqev3keg.public.blob.vercel-storage.com/infographics/mod-2-11/fc-2-11-2.png' },
  "fc-2-11-3": { uri: 'https://8mnwcjygpqev3keg.public.blob.vercel-storage.com/infographics/mod-2-11/fc-2-11-3.png' },
  "fc-2-11-4": { uri: 'https://8mnwcjygpqev3keg.public.blob.vercel-storage.com/infographics/mod-2-11/fc-2-11-4.png' },
  "fc-2-11-5": { uri: 'https://8mnwcjygpqev3keg.public.blob.vercel-storage.com/infographics/mod-2-11/fc-2-11-5.png' },
  "fc-2-11-6": { uri: 'https://8mnwcjygpqev3keg.public.blob.vercel-storage.com/infographics/mod-2-11/fc-2-11-6.png' },
  // Module 2-12: פנסיה
  "fc-2-12-1": { uri: 'https://8mnwcjygpqev3keg.public.blob.vercel-storage.com/infographics/mod-2-12/fc-2-12-1.png' },
  "fc-2-12-2": { uri: 'https://8mnwcjygpqev3keg.public.blob.vercel-storage.com/infographics/mod-2-12/fc-2-12-2.png' },
  "fc-2-12-3": { uri: 'https://8mnwcjygpqev3keg.public.blob.vercel-storage.com/infographics/mod-2-12/fc-2-12-3.png' },
  "fc-2-12-4": { uri: 'https://8mnwcjygpqev3keg.public.blob.vercel-storage.com/infographics/mod-2-12/fc-2-12-4.png' },
  "fc-2-12-5": { uri: 'https://8mnwcjygpqev3keg.public.blob.vercel-storage.com/infographics/mod-2-12/fc-2-12-5.png' },
  "fc-2-12-6": { uri: 'https://8mnwcjygpqev3keg.public.blob.vercel-storage.com/infographics/mod-2-12/fc-2-12-6.png' },
  // Module 2-13: קרן השתלמות
  "fc-2-13-1": { uri: 'https://8mnwcjygpqev3keg.public.blob.vercel-storage.com/infographics/mod-2-13/fc-2-13-1.png' },
  "fc-2-13-2": { uri: 'https://8mnwcjygpqev3keg.public.blob.vercel-storage.com/infographics/mod-2-13/fc-2-13-2.png' },
  "fc-2-13-3": { uri: 'https://8mnwcjygpqev3keg.public.blob.vercel-storage.com/infographics/mod-2-13/fc-2-13-3.png' },
  "fc-2-13-4": { uri: 'https://8mnwcjygpqev3keg.public.blob.vercel-storage.com/infographics/mod-2-13/fc-2-13-4.png' },
  "fc-2-13-5": { uri: 'https://8mnwcjygpqev3keg.public.blob.vercel-storage.com/infographics/mod-2-13/fc-2-13-5.png' },
  "fc-2-13-6": { uri: 'https://8mnwcjygpqev3keg.public.blob.vercel-storage.com/infographics/mod-2-13/fc-2-13-6.png' },
  // Module 2-14: ביטוחים
  "fc-2-14-1": { uri: 'https://8mnwcjygpqev3keg.public.blob.vercel-storage.com/infographics/mod-2-14/fc-2-14-1.png' },
  "fc-2-14-2": { uri: 'https://8mnwcjygpqev3keg.public.blob.vercel-storage.com/infographics/mod-2-14/fc-2-14-2.png' },
  "fc-2-14-3": { uri: 'https://8mnwcjygpqev3keg.public.blob.vercel-storage.com/infographics/mod-2-14/fc-2-14-3.png' },
  "fc-2-14-4": { uri: 'https://8mnwcjygpqev3keg.public.blob.vercel-storage.com/infographics/mod-2-14/fc-2-14-4.png' },
  "fc-2-14-5": { uri: 'https://8mnwcjygpqev3keg.public.blob.vercel-storage.com/infographics/mod-2-14/fc-2-14-5.png' },
  "fc-2-14-6": { uri: 'https://8mnwcjygpqev3keg.public.blob.vercel-storage.com/infographics/mod-2-14/fc-2-14-6.png' },

  // ═══════════════════════════════════════════════════════════════
  // CHAPTER 3: יציבות 
  // ═══════════════════════════════════════════════════════════════

  // Module 3-15: אינפלציה 
  "fc-3-15-1": { uri: 'https://8mnwcjygpqev3keg.public.blob.vercel-storage.com/infographics/mod-3-15/fc-3-15-1.png' },
  "fc-3-15-2": { uri: 'https://8mnwcjygpqev3keg.public.blob.vercel-storage.com/infographics/mod-3-15/fc-3-15-2.png' },
  "fc-3-15-3": { uri: 'https://8mnwcjygpqev3keg.public.blob.vercel-storage.com/infographics/mod-3-15/fc-3-15-3.png' },
  "fc-3-15-4": { uri: 'https://8mnwcjygpqev3keg.public.blob.vercel-storage.com/infographics/mod-3-15/fc-3-15-4.png' },
  "fc-3-15-5": { uri: 'https://8mnwcjygpqev3keg.public.blob.vercel-storage.com/infographics/mod-3-15/fc-3-15-5.png' },
  "fc-3-15-6": { uri: 'https://8mnwcjygpqev3keg.public.blob.vercel-storage.com/infographics/mod-3-15/fc-3-15-6.png' },
  
  // Module 3-16: הפסיכולוגיה של הכסף
  "fc-3-16-1": { uri: 'https://8mnwcjygpqev3keg.public.blob.vercel-storage.com/infographics/mod-3-16/fc-3-16-1.png' },
  "fc-3-16-2": { uri: 'https://8mnwcjygpqev3keg.public.blob.vercel-storage.com/infographics/mod-3-16/fc-3-16-2.png' },
  "fc-3-16-3": { uri: 'https://8mnwcjygpqev3keg.public.blob.vercel-storage.com/infographics/mod-3-16/fc-3-16-3.png' },
  "fc-3-16-4": { uri: 'https://8mnwcjygpqev3keg.public.blob.vercel-storage.com/infographics/mod-3-16/fc-3-16-4.png' },
  "fc-3-16-5": { uri: 'https://8mnwcjygpqev3keg.public.blob.vercel-storage.com/infographics/mod-3-16/fc-3-16-5.png' },
  "fc-3-16-6": { uri: 'https://8mnwcjygpqev3keg.public.blob.vercel-storage.com/infographics/mod-3-16/fc-3-16-6.png' },
  
  // Module 3-17: קופת גמל להשקעה
  "fc-3-17-1": { uri: 'https://8mnwcjygpqev3keg.public.blob.vercel-storage.com/infographics/mod-3-17/fc-3-17-1.png' },
  "fc-3-17-2": { uri: 'https://8mnwcjygpqev3keg.public.blob.vercel-storage.com/infographics/mod-3-17/fc-3-17-2.png' },
  "fc-3-17-3": { uri: 'https://8mnwcjygpqev3keg.public.blob.vercel-storage.com/infographics/mod-3-17/fc-3-17-3.png' },
  "fc-3-17-4": { uri: 'https://8mnwcjygpqev3keg.public.blob.vercel-storage.com/infographics/mod-3-17/fc-3-17-4.png' },
  "fc-3-17-5": { uri: 'https://8mnwcjygpqev3keg.public.blob.vercel-storage.com/infographics/mod-3-17/fc-3-17-5.png' },
  "fc-3-17-6": { uri: 'https://8mnwcjygpqev3keg.public.blob.vercel-storage.com/infographics/mod-3-17/fc-3-17-6.png' },

  // Module 3-18
  "fc-3-18-1": { uri: 'https://8mnwcjygpqev3keg.public.blob.vercel-storage.com/infographics/mod-3-18/fc-3-18-1.png' },
  "fc-3-18-2": { uri: 'https://8mnwcjygpqev3keg.public.blob.vercel-storage.com/infographics/mod-3-18/fc-3-18-2.png' },
  "fc-3-18-3": { uri: 'https://8mnwcjygpqev3keg.public.blob.vercel-storage.com/infographics/mod-3-18/fc-3-18-3.png' },
  "fc-3-18-4": { uri: 'https://8mnwcjygpqev3keg.public.blob.vercel-storage.com/infographics/mod-3-18/fc-3-18-4.png' },
  "fc-3-18-5": { uri: 'https://8mnwcjygpqev3keg.public.blob.vercel-storage.com/infographics/mod-3-18/fc-3-18-5.png' },
  "fc-3-18-6": { uri: 'https://8mnwcjygpqev3keg.public.blob.vercel-storage.com/infographics/mod-3-18/fc-3-18-6.png' },


  // ═══════════════════════════════════════════════════════════════
  // CHAPTER 4: צמיחה
  // ═══════════════════════════════════════════════════════════════

  // Module 4-19: שוק ההון
  "fc-4-19-1": { uri: 'https://8mnwcjygpqev3keg.public.blob.vercel-storage.com/infographics/mod-4-19/fc-4-19-1.png' },
  "fc-4-19-2": { uri: 'https://8mnwcjygpqev3keg.public.blob.vercel-storage.com/infographics/mod-4-19/fc-4-19-2.png' },
  "fc-4-19-3": { uri: 'https://8mnwcjygpqev3keg.public.blob.vercel-storage.com/infographics/mod-4-19/fc-4-19-3.png' },
  "fc-4-19-4": { uri: 'https://8mnwcjygpqev3keg.public.blob.vercel-storage.com/infographics/mod-4-19/fc-4-19-4.png' },
  "fc-4-19-5": { uri: 'https://8mnwcjygpqev3keg.public.blob.vercel-storage.com/infographics/mod-4-19/fc-4-19-5.png' },
  "fc-4-19-6": { uri: 'https://8mnwcjygpqev3keg.public.blob.vercel-storage.com/infographics/mod-4-19/fc-4-19-6.png' },

  // Module 4-20: מדדים
  "fc-4-20-1": { uri: 'https://8mnwcjygpqev3keg.public.blob.vercel-storage.com/infographics/mod-4-20/fc-4-20-1.png' },
  "fc-4-20-2": { uri: 'https://8mnwcjygpqev3keg.public.blob.vercel-storage.com/infographics/mod-4-20/fc-4-20-2.png' },
  "fc-4-20-3": { uri: 'https://8mnwcjygpqev3keg.public.blob.vercel-storage.com/infographics/mod-4-20/fc-4-20-3.png' },
  "fc-4-20-4": { uri: 'https://8mnwcjygpqev3keg.public.blob.vercel-storage.com/infographics/mod-4-20/fc-4-20-4.png' },
  "fc-4-20-5": { uri: 'https://8mnwcjygpqev3keg.public.blob.vercel-storage.com/infographics/mod-4-20/fc-4-20-5.png' },
  "fc-4-20-6": { uri: 'https://8mnwcjygpqev3keg.public.blob.vercel-storage.com/infographics/mod-4-20/fc-4-20-6.png' },

  // Module 4-21: תעודות סל (PRO)
  "fc-4-21-1": { uri: 'https://8mnwcjygpqev3keg.public.blob.vercel-storage.com/infographics/mod-4-21/fc-4-21-1.png' },
  "fc-4-21-2": { uri: 'https://8mnwcjygpqev3keg.public.blob.vercel-storage.com/infographics/mod-4-21/fc-4-21-2.png' },
  "fc-4-21-3": { uri: 'https://8mnwcjygpqev3keg.public.blob.vercel-storage.com/infographics/mod-4-21/fc-4-21-3.png' },
  "fc-4-21-4": { uri: 'https://8mnwcjygpqev3keg.public.blob.vercel-storage.com/infographics/mod-4-21/fc-4-21-4.png' },
  "fc-4-21-5": { uri: 'https://8mnwcjygpqev3keg.public.blob.vercel-storage.com/infographics/mod-4-21/fc-4-21-5.png' },
  "fc-4-21-6": { uri: 'https://8mnwcjygpqev3keg.public.blob.vercel-storage.com/infographics/mod-4-21/fc-4-21-6.png' },

  // Module 4-22: פקודות מסחר
  "fc-4-22-1": { uri: 'https://8mnwcjygpqev3keg.public.blob.vercel-storage.com/infographics/mod-4-22/fc-4-22-1.png' },
  "fc-4-22-2": { uri: 'https://8mnwcjygpqev3keg.public.blob.vercel-storage.com/infographics/mod-4-22/fc-4-22-2.png' },
  "fc-4-22-3": { uri: 'https://8mnwcjygpqev3keg.public.blob.vercel-storage.com/infographics/mod-4-22/fc-4-22-3.png' },
  "fc-4-22-4": { uri: 'https://8mnwcjygpqev3keg.public.blob.vercel-storage.com/infographics/mod-4-22/fc-4-22-4.png' },
  "fc-4-22-5": { uri: 'https://8mnwcjygpqev3keg.public.blob.vercel-storage.com/infographics/mod-4-22/fc-4-22-5.png' },
  "fc-4-22-6": { uri: 'https://8mnwcjygpqev3keg.public.blob.vercel-storage.com/infographics/mod-4-22/fc-4-22-6.png' },

  // Module 4-23: דיבידנד
  "fc-4-23-1": { uri: 'https://8mnwcjygpqev3keg.public.blob.vercel-storage.com/infographics/mod-4-23/fc-4-23-1.png' },
  "fc-4-23-2": { uri: 'https://8mnwcjygpqev3keg.public.blob.vercel-storage.com/infographics/mod-4-23/fc-4-23-2.png' },
  "fc-4-23-3": { uri: 'https://8mnwcjygpqev3keg.public.blob.vercel-storage.com/infographics/mod-4-23/fc-4-23-3.png' },
  "fc-4-23-4": { uri: 'https://8mnwcjygpqev3keg.public.blob.vercel-storage.com/infographics/mod-4-23/fc-4-23-4.png' },
  "fc-4-23-5": { uri: 'https://8mnwcjygpqev3keg.public.blob.vercel-storage.com/infographics/mod-4-23/fc-4-23-5.png' },
  "fc-4-23-6": { uri: 'https://8mnwcjygpqev3keg.public.blob.vercel-storage.com/infographics/mod-4-23/fc-4-23-6.png' },

  // Module 4-24: פיזור וניהול סיכונים (PRO)
  "fc-4-24-1": { uri: 'https://8mnwcjygpqev3keg.public.blob.vercel-storage.com/infographics/mod-4-24/fc-4-24-1.png' },
  "fc-4-24-2": { uri: 'https://8mnwcjygpqev3keg.public.blob.vercel-storage.com/infographics/mod-4-24/fc-4-24-2.png' },
  "fc-4-24-3": { uri: 'https://8mnwcjygpqev3keg.public.blob.vercel-storage.com/infographics/mod-4-24/fc-4-24-3.png' },
  "fc-4-24-4": { uri: 'https://8mnwcjygpqev3keg.public.blob.vercel-storage.com/infographics/mod-4-24/fc-4-24-4.png' },
  "fc-4-24-5": { uri: 'https://8mnwcjygpqev3keg.public.blob.vercel-storage.com/infographics/mod-4-24/fc-4-24-5.png' },
  "fc-4-24-6": { uri: 'https://8mnwcjygpqev3keg.public.blob.vercel-storage.com/infographics/mod-4-24/fc-4-24-6.png' },

  // Module 4-25
  "fc-4-25-0a": require("../../../assets/IMAGES/flashcard-etf-screenshot.png"),
  "fc-4-25-0b": require("../../../assets/IMAGES/flashcard-etf-screenshot.png"),
  "fc-4-25-0c": require("../../../assets/IMAGES/flashcard-etf-screenshot.png"),
  "fc-4-25-1": { uri: 'https://8mnwcjygpqev3keg.public.blob.vercel-storage.com/infographics/mod-4-25/fc-4-25-1.png' },
  "fc-4-25-2": { uri: 'https://8mnwcjygpqev3keg.public.blob.vercel-storage.com/infographics/mod-4-25/fc-4-25-2.png' },
  "fc-4-25-3": { uri: 'https://8mnwcjygpqev3keg.public.blob.vercel-storage.com/infographics/mod-4-25/fc-4-25-3.png' },
  "fc-4-25-4": { uri: 'https://8mnwcjygpqev3keg.public.blob.vercel-storage.com/infographics/mod-4-25/fc-4-25-4.png' },
  "fc-4-25-5": { uri: 'https://8mnwcjygpqev3keg.public.blob.vercel-storage.com/infographics/mod-4-25/fc-4-25-5.png' },
  "fc-4-25-6": { uri: 'https://8mnwcjygpqev3keg.public.blob.vercel-storage.com/infographics/mod-4-25/fc-4-25-6.png' },

  // Module 4-26
  "fc-4-26-1": { uri: 'https://8mnwcjygpqev3keg.public.blob.vercel-storage.com/infographics/mod-4-26/fc-4-26-1.png' },
  "fc-4-26-2": { uri: 'https://8mnwcjygpqev3keg.public.blob.vercel-storage.com/infographics/mod-4-26/fc-4-26-2.png' },
  "fc-4-26-3": { uri: 'https://8mnwcjygpqev3keg.public.blob.vercel-storage.com/infographics/mod-4-26/fc-4-26-3.png' },
  "fc-4-26-4": { uri: 'https://8mnwcjygpqev3keg.public.blob.vercel-storage.com/infographics/mod-4-26/fc-4-26-4.png' },
  "fc-4-26-5": { uri: 'https://8mnwcjygpqev3keg.public.blob.vercel-storage.com/infographics/mod-4-26/fc-4-26-5.png' },
  "fc-4-26-6": { uri: 'https://8mnwcjygpqev3keg.public.blob.vercel-storage.com/infographics/mod-4-26/fc-4-26-6.png' },

  // Module 4-27
  "fc-4-27-1": { uri: 'https://8mnwcjygpqev3keg.public.blob.vercel-storage.com/infographics/mod-4-27/fc-4-27-1.png' },
  "fc-4-27-2": { uri: 'https://8mnwcjygpqev3keg.public.blob.vercel-storage.com/infographics/mod-4-27/fc-4-27-2.png' },
  "fc-4-27-3": { uri: 'https://8mnwcjygpqev3keg.public.blob.vercel-storage.com/infographics/mod-4-27/fc-4-27-3.png' },
  "fc-4-27-4": { uri: 'https://8mnwcjygpqev3keg.public.blob.vercel-storage.com/infographics/mod-4-27/fc-4-27-4.png' },
  "fc-4-27-5": { uri: 'https://8mnwcjygpqev3keg.public.blob.vercel-storage.com/infographics/mod-4-27/fc-4-27-5.png' },
  "fc-4-27-6": { uri: 'https://8mnwcjygpqev3keg.public.blob.vercel-storage.com/infographics/mod-4-27/fc-4-27-6.png' },

  // Module 4-28
  "fc-4-28-1": { uri: 'https://8mnwcjygpqev3keg.public.blob.vercel-storage.com/infographics/mod-4-28/fc-4-28-1.png' },
  "fc-4-28-2": { uri: 'https://8mnwcjygpqev3keg.public.blob.vercel-storage.com/infographics/mod-4-28/fc-4-28-2.png' },
  "fc-4-28-3": { uri: 'https://8mnwcjygpqev3keg.public.blob.vercel-storage.com/infographics/mod-4-28/fc-4-28-3.png' },
  "fc-4-28-4": { uri: 'https://8mnwcjygpqev3keg.public.blob.vercel-storage.com/infographics/mod-4-28/fc-4-28-4.png' },
  "fc-4-28-5": { uri: 'https://8mnwcjygpqev3keg.public.blob.vercel-storage.com/infographics/mod-4-28/fc-4-28-5.png' },
  "fc-4-28-6": { uri: 'https://8mnwcjygpqev3keg.public.blob.vercel-storage.com/infographics/mod-4-28/fc-4-28-6.png' },

  // Module 4-29
  "fc-4-29-1": { uri: 'https://8mnwcjygpqev3keg.public.blob.vercel-storage.com/infographics/mod-4-29/fc-4-29-1.png' },
  "fc-4-29-2": { uri: 'https://8mnwcjygpqev3keg.public.blob.vercel-storage.com/infographics/mod-4-29/fc-4-29-2.png' },
  "fc-4-29-3": { uri: 'https://8mnwcjygpqev3keg.public.blob.vercel-storage.com/infographics/mod-4-29/fc-4-29-3.png' },
  "fc-4-29-4": { uri: 'https://8mnwcjygpqev3keg.public.blob.vercel-storage.com/infographics/mod-4-29/fc-4-29-4.png' },
  "fc-4-29-5": { uri: 'https://8mnwcjygpqev3keg.public.blob.vercel-storage.com/infographics/mod-4-29/fc-4-29-5.png' },
  "fc-4-29-6": { uri: 'https://8mnwcjygpqev3keg.public.blob.vercel-storage.com/infographics/mod-4-29/fc-4-29-6.png' },

  // Module 4-30
  "fc-4-30-1": { uri: 'https://8mnwcjygpqev3keg.public.blob.vercel-storage.com/infographics/mod-4-30/fc-4-30-1.png' },
  "fc-4-30-2": { uri: 'https://8mnwcjygpqev3keg.public.blob.vercel-storage.com/infographics/mod-4-30/fc-4-30-2.png' },
  "fc-4-30-3": { uri: 'https://8mnwcjygpqev3keg.public.blob.vercel-storage.com/infographics/mod-4-30/fc-4-30-3.png' },
  "fc-4-30-4": { uri: 'https://8mnwcjygpqev3keg.public.blob.vercel-storage.com/infographics/mod-4-30/fc-4-30-4.png' },
  "fc-4-30-5": { uri: 'https://8mnwcjygpqev3keg.public.blob.vercel-storage.com/infographics/mod-4-30/fc-4-30-5.png' },
  "fc-4-30-6": { uri: 'https://8mnwcjygpqev3keg.public.blob.vercel-storage.com/infographics/mod-4-30/fc-4-30-6.png' },

  // ── Graham Bonus Modules ──
  // Module 4-b1: בנה תיק לפי גראהם (RESTORED PER USER REQUEST)
  "fc-4-b1-1": { uri: 'https://8mnwcjygpqev3keg.public.blob.vercel-storage.com/infographics/mod-4-b1/fc-4-b1-1.png' },
  "fc-4-b1-2": { uri: 'https://8mnwcjygpqev3keg.public.blob.vercel-storage.com/infographics/mod-4-b1/fc-4-b1-2.png' },
  "fc-4-b1-2b": { uri: 'https://8mnwcjygpqev3keg.public.blob.vercel-storage.com/infographics/mod-4-b1/fc-4-b1-2.png' },
  "fc-4-b1-3": { uri: 'https://8mnwcjygpqev3keg.public.blob.vercel-storage.com/infographics/mod-4-b1/fc-4-b1-3.png' },
  // Module 4-b2: מחשבון מרווח ביטחון
  "fc-4-b2-1": { uri: 'https://8mnwcjygpqev3keg.public.blob.vercel-storage.com/infographics/mod-4-b2/fc-4-b2-1.png' },
  "fc-4-b2-2": { uri: 'https://8mnwcjygpqev3keg.public.blob.vercel-storage.com/infographics/mod-4-b2/fc-4-b2-2.png' },
  // Module 4-b3: מחיר vs. ערך
  "fc-4-b3-1": { uri: 'https://8mnwcjygpqev3keg.public.blob.vercel-storage.com/infographics/mod-4-b3/fc-4-b3-1.png' },
  "fc-4-b3-2": { uri: 'https://8mnwcjygpqev3keg.public.blob.vercel-storage.com/infographics/mod-4-b3/fc-4-b3-2.png' },
  // Module 4-b4: ציר הזמן של המשברים
  "fc-4-b4-1": { uri: 'https://8mnwcjygpqev3keg.public.blob.vercel-storage.com/infographics/mod-4-b4/fc-4-b4-1.png' },
  "fc-4-b4-2": { uri: 'https://8mnwcjygpqev3keg.public.blob.vercel-storage.com/infographics/mod-4-b4/fc-4-b4-2.png' },

  // ═══════════════════════════════════════════════════════════════
  // CHAPTER 5: חופש כלכלי
  // ═══════════════════════════════════════════════════════════════

  // Module 5-25: FIRE
  "fc-5-25-1": { uri: 'https://8mnwcjygpqev3keg.public.blob.vercel-storage.com/infographics/mod-5-25/fc-5-25-1.png' },
  "fc-5-25-2": { uri: 'https://8mnwcjygpqev3keg.public.blob.vercel-storage.com/infographics/mod-5-25/fc-5-25-2.png' },
  "fc-5-25-3": { uri: 'https://8mnwcjygpqev3keg.public.blob.vercel-storage.com/infographics/mod-5-25/fc-5-25-3.png' },
  "fc-5-25-4": { uri: 'https://8mnwcjygpqev3keg.public.blob.vercel-storage.com/infographics/mod-5-25/fc-5-25-4.png' },
  "fc-5-25-5": { uri: 'https://8mnwcjygpqev3keg.public.blob.vercel-storage.com/infographics/mod-5-25/fc-5-25-5.png' },
  "fc-5-25-6": { uri: 'https://8mnwcjygpqev3keg.public.blob.vercel-storage.com/infographics/mod-5-25/fc-5-25-6.png' },

  // Module 5-26: נדל"ן ומשכנתא (PRO)
  "fc-5-26-1": { uri: 'https://8mnwcjygpqev3keg.public.blob.vercel-storage.com/infographics/mod-5-26/fc-5-26-1.png' },
  "fc-5-26-2": { uri: 'https://8mnwcjygpqev3keg.public.blob.vercel-storage.com/infographics/mod-5-26/fc-5-26-2.png' },
  "fc-5-26-3": { uri: 'https://8mnwcjygpqev3keg.public.blob.vercel-storage.com/infographics/mod-5-26/fc-5-26-3.png' },
  "fc-5-26-4": { uri: 'https://8mnwcjygpqev3keg.public.blob.vercel-storage.com/infographics/mod-5-26/fc-5-26-4.png' },
  "fc-5-26-5": { uri: 'https://8mnwcjygpqev3keg.public.blob.vercel-storage.com/infographics/mod-5-26/fc-5-26-5.png' },
  "fc-5-26-6": { uri: 'https://8mnwcjygpqev3keg.public.blob.vercel-storage.com/infographics/mod-5-26/fc-5-26-6.png' },

  // Module 5-27: REIT (PRO)
  "fc-5-27-1": { uri: 'https://8mnwcjygpqev3keg.public.blob.vercel-storage.com/infographics/mod-5-27/fc-5-27-1.png' },
  "fc-5-27-2": { uri: 'https://8mnwcjygpqev3keg.public.blob.vercel-storage.com/infographics/mod-5-27/fc-5-27-2.png' },
  "fc-5-27-3": { uri: 'https://8mnwcjygpqev3keg.public.blob.vercel-storage.com/infographics/mod-5-27/fc-5-27-3.png' },
  "fc-5-27-4": { uri: 'https://8mnwcjygpqev3keg.public.blob.vercel-storage.com/infographics/mod-5-27/fc-5-27-4.png' },
  "fc-5-27-5": { uri: 'https://8mnwcjygpqev3keg.public.blob.vercel-storage.com/infographics/mod-5-27/fc-5-27-5.png' },
  "fc-5-27-6": { uri: 'https://8mnwcjygpqev3keg.public.blob.vercel-storage.com/infographics/mod-5-27/fc-5-27-6.png' },

  // Module 5-28: תכנון פרישה (PRO)
  "fc-5-28-1": { uri: 'https://8mnwcjygpqev3keg.public.blob.vercel-storage.com/infographics/mod-5-28/fc-5-28-1.png' },
  "fc-5-28-2": { uri: 'https://8mnwcjygpqev3keg.public.blob.vercel-storage.com/infographics/mod-5-28/fc-5-28-2.png' },
  "fc-5-28-3": { uri: 'https://8mnwcjygpqev3keg.public.blob.vercel-storage.com/infographics/mod-5-28/fc-5-28-3.png' },
  "fc-5-28-4": { uri: 'https://8mnwcjygpqev3keg.public.blob.vercel-storage.com/infographics/mod-5-28/fc-5-28-4.png' },
  "fc-5-28-5": { uri: 'https://8mnwcjygpqev3keg.public.blob.vercel-storage.com/infographics/mod-5-28/fc-5-28-5.png' },
  "fc-5-28-6": { uri: 'https://8mnwcjygpqev3keg.public.blob.vercel-storage.com/infographics/mod-5-28/fc-5-28-6.png' },
  
  // Module 5-29: העברה דורית (PRO)
  "fc-5-29-1": { uri: 'https://8mnwcjygpqev3keg.public.blob.vercel-storage.com/infographics/mod-5-29/fc-5-29-1.png' },
  "fc-5-29-2": { uri: 'https://8mnwcjygpqev3keg.public.blob.vercel-storage.com/infographics/mod-5-29/fc-5-29-2.png' },
  "fc-5-29-3": { uri: 'https://8mnwcjygpqev3keg.public.blob.vercel-storage.com/infographics/mod-5-29/fc-5-29-3.png' },
  "fc-5-29-4": { uri: 'https://8mnwcjygpqev3keg.public.blob.vercel-storage.com/infographics/mod-5-29/fc-5-29-4.png' },
  "fc-5-29-5": { uri: 'https://8mnwcjygpqev3keg.public.blob.vercel-storage.com/infographics/mod-5-29/fc-5-29-5.png' },
  "fc-5-29-6": { uri: 'https://8mnwcjygpqev3keg.public.blob.vercel-storage.com/infographics/mod-5-29/fc-5-29-6.png' },

  // Module 5-30
  "fc-5-30-1": { uri: 'https://8mnwcjygpqev3keg.public.blob.vercel-storage.com/infographics/mod-5-30/fc-5-30-1.png' },
  "fc-5-30-2": { uri: 'https://8mnwcjygpqev3keg.public.blob.vercel-storage.com/infographics/mod-5-30/fc-5-30-2.png' },
  "fc-5-30-3": { uri: 'https://8mnwcjygpqev3keg.public.blob.vercel-storage.com/infographics/mod-5-30/fc-5-30-3.png' },
  "fc-5-30-4": { uri: 'https://8mnwcjygpqev3keg.public.blob.vercel-storage.com/infographics/mod-5-30/fc-5-30-4.png' },
  "fc-5-30-5": { uri: 'https://8mnwcjygpqev3keg.public.blob.vercel-storage.com/infographics/mod-5-30/fc-5-30-5.png' },
  "fc-5-30-6": { uri: 'https://8mnwcjygpqev3keg.public.blob.vercel-storage.com/infographics/mod-5-30/fc-5-30-6.png' },

  // Module 5-31 (IRA) removed — module deleted due to content accuracy concerns.
};

/** Old summary infographics, used as decoration between flashcards (1.5s splash) */
export const MODULE_SUMMARY_DECORATION: Record<string, { uri: string }> = {
};

/** Cards whose infographic PNG has a light/white background, use light container */
const LIGHT_BG_CARDS = new Set(["fc-1-4-4"]);

/** Cards whose infographic should be shown smaller so text + image fits on one page */
const COMPACT_CARDS = new Set(["fc-3-15-6", "fc-4-25-0a"]);

/** Cards whose infographic should be shown larger (infographic-top layout) */
const LARGE_CARDS = new Set([
  "fc-1-5-1", "fc-1-5-2", "fc-1-5-3", "fc-1-5-4", "fc-1-5-5", "fc-1-5-6",
  "fc-1-6-1", "fc-1-6-2", "fc-1-6-3", "fc-1-6-4", "fc-1-6-5", "fc-1-6-6",
  // Graham bonus modules, use top-layout so image fills the upper area
  "fc-4-b1-1", "fc-4-b1-2", "fc-4-b1-2b", "fc-4-b1-3",
  "fc-4-b2-1", "fc-4-b2-2",
  "fc-4-b3-1", "fc-4-b3-2",
  // fc-4-b4-1, fc-4-b4-2 removed, they have substantial text that needs to be visible
]);

/** Cards whose infographic should fill the container edge-to-edge (cover instead of contain) */
const COVER_CARDS = new Set(["fc-1-3-2"]);

interface TextOverlay {
  topPct: number;
  leftPct: number;
  widthPct: number;
  heightPct: number;
  text?: string;
  fontSize?: number;
  color?: string;
  backgroundColor?: string;
}

/** Patches over typos in cloud-hosted PNG infographics. Position % is relative to the rendered image. */
const TEXT_OVERLAYS: Record<string, TextOverlay[]> = {
  "fc-1-2-1": [
    {
      topPct: 78,
      leftPct: 38,
      widthPct: 13,
      heightPct: 3,
      backgroundColor: "#e0f2fe",
    },
  ],
};

// Route every remote infographic / Finn image through our /api/img proxy in
// prod to dodge Vercel Blob's per-client http_403 (see toProxiedImageUri).
// Mutates the exported maps in place at module load — synchronously, before any
// consumer (this component OR LessonFlowScreen's prefetch) reads them. No-op in
// dev and for non-Blob/bundled entries.
function proxyImageMapInPlace(map: Record<string, unknown>): void {
  for (const k of Object.keys(map)) {
    const v = map[k];
    if (v && typeof v === "object" && "uri" in v && typeof (v as { uri: unknown }).uri === "string") {
      map[k] = { ...(v as object), uri: toProxiedImageUri((v as { uri: string }).uri) };
    }
  }
}
proxyImageMapInPlace(INFOGRAPHIC_MAP as unknown as Record<string, unknown>);
proxyImageMapInPlace(FINN_MAP as unknown as Record<string, unknown>);

// Bundled chapter-0 infographics (Yoav 2026-06-26). mod-0-1 / mod-0-1b are the
// FIRST module a new user sees; their flashcard infographics kept rendering BLANK
// on device — Vercel Blob's per-client http_403 burst outlasts the retry ladder
// above (same reason chapter-0 intro AUDIO is bundled, see useIntroAudio's
// BUNDLED_INTRO_AUDIO). These 5 images ship in the binary → instant, offline,
// immune to the CDN. Keyed by cardId; takes precedence over INFOGRAPHIC_MAP + the
// proxy. mod-0-1 uses fc-0-2-1..3, mod-0-1b uses fc-0-2-4..5. Other chapters keep
// the proxy path. (mod-0-2 folder is the post-split legacy location for mod-0-1's
// cards, like the audio filename trap.)
// ⚠️ Stored as .jpg, NOT .png: the blob serves these as JPEG bytes even under a
// .png name. AAPT runs its PNG cruncher on .png drawables and a JPEG-as-.png
// FAILS the Android build ("file failed to compile" — Yoav 2026-06-26). .jpg
// drawables are copied as-is (no cruncher), and JPEG is the true source format.
/* eslint-disable @typescript-eslint/no-require-imports */
const BUNDLED_INFOGRAPHIC: Record<string, number> = {
  'fc-0-2-1': require('../../../assets/infographics/fc-0-2-1.jpg'),
  'fc-0-2-2': require('../../../assets/infographics/fc-0-2-2.jpg'),
  'fc-0-2-3': require('../../../assets/infographics/fc-0-2-3.jpg'),
  'fc-0-2-4': require('../../../assets/infographics/fc-0-2-4.jpg'),
  'fc-0-2-5': require('../../../assets/infographics/fc-0-2-5.jpg'),
};
/* eslint-enable @typescript-eslint/no-require-imports */

interface Props {
  cardId: string;
  diveStep?: number;
  zoomRegions?: [number, number, number][];
}

// Retry policy for transient image-load failures. iOS CFNetwork errors 303
// + Vercel Blob intermittent 403s have been observed for the same URLs that
// curl perfectly (PostHog 2026-06-05: 7 hits on fc-0-2-3 in a single day).
// Lengthened 2026-06-19: a 2-step ladder gave up too early — the per-client
// Vercel Blob 403 episodes outlast it (see useModulePrefetch note), so module
// infographics stayed BLANK for throttled users while pearl videos (Range-
// streamed) still loaded. 4 steps (~21s) clears the shorter episodes; a
// shimmer skeleton keeps the slot from looking broken while it retries. The
// definitive fix for sustained per-client 403s is moving infographics off
// Vercel Blob (R2 / image-proxy CDN).
const IMAGE_RETRY_DELAYS_MS = [800, 2400, 6000, 12000] as const;

export function FlashcardInfographic({ cardId, diveStep = 0, zoomRegions }: Props) {
  // Prefer the bundled (binary) asset when present — it can't 403 and loads
  // instantly/offline. Falls back to the proxied remote URL for every other card.
  const bundledSource = BUNDLED_INFOGRAPHIC[cardId] as number | undefined;
  const baseSource: ImageSource | number | null =
    bundledSource !== undefined ? bundledSource : INFOGRAPHIC_MAP[cardId];
  const lottieSource = LOTTIE_MAP[cardId];
  const finnTapSource = FINN_TAP_MAP[cardId];
  const isLightBg = LIGHT_BG_CARDS.has(cardId);
  const [ratio, setRatio] = useState<number | undefined>(undefined);
  const [finnFullscreen, setFinnFullscreen] = useState(false);
  const [imageError, setImageError] = useState(false);
  const [retryAttempt, setRetryAttempt] = useState(0);
  // Drives the shimmer skeleton: false until the image actually paints. Web
  // never fires onLoad here (handleLoad is native-only), so seed it true there.
  const [loaded, setLoaded] = useState(Platform.OS === 'web');
  const retryTimerRef = useRef<ReturnType<typeof setTimeout> | null>(null);

  useEffect(() => () => {
    if (retryTimerRef.current) clearTimeout(retryTimerRef.current);
  }, []);

  // Reset retry state when the cardId changes so a new flashcard gets a
  // fresh budget of attempts instead of inheriting the previous card's count.
  useEffect(() => {
    setImageError(false);
    setRetryAttempt(0);
    if (retryTimerRef.current) {
      clearTimeout(retryTimerRef.current);
      retryTimerRef.current = null;
    }
  }, [cardId]);

  // Re-show the skeleton whenever the image (re)mounts — new card or a retry
  // (the <AnimatedExpoImage> key includes retryAttempt, so it remounts).
  useEffect(() => {
    if (Platform.OS !== 'web') setLoaded(false);
  }, [cardId, retryAttempt]);

  // On retry, append ?r=N to the URI so ExpoImage's memory-disk cache cannot
  // serve a previously-cached failure for the same URL. The original entry
  // stays untouched in INFOGRAPHIC_MAP; only the in-flight request is busted.
  const source: ImageSource | number | null = (() => {
    // Bundled (number) sources never fail → no cache-busting / retry needed.
    if (!baseSource || typeof baseSource === 'number') return baseSource;
    if (retryAttempt === 0) return baseSource;
    if (typeof baseSource === 'object' && 'uri' in baseSource && typeof baseSource.uri === 'string') {
      const sep = baseSource.uri.includes('?') ? '&' : '?';
      return { ...baseSource, uri: `${baseSource.uri}${sep}r=${retryAttempt}` };
    }
    return baseSource;
  })();

  const handleLoad = useCallback((e: ImageLoadEventData) => {
    setLoaded(true);
    const { width, height } = e.source;
    if (width && height) {
      setRatio(width / height);
    }
    if (retryAttempt > 0) {
      const rawUri = typeof baseSource === 'object' && baseSource && 'uri' in baseSource ? baseSource.uri : undefined;
      captureEvent('infographic_load_recovered', {
        card_id: cardId,
        uri: typeof rawUri === 'string' ? rawUri : 'bundled',
        attempts: retryAttempt + 1,
        platform: Platform.OS,
      });
    }
  }, [cardId, baseSource, retryAttempt]);

  const handleImageError = useCallback((err: unknown) => {
    if (retryAttempt < IMAGE_RETRY_DELAYS_MS.length) {
      const delay = IMAGE_RETRY_DELAYS_MS[retryAttempt];
      const nextAttempt = retryAttempt + 1;
      if (retryTimerRef.current) clearTimeout(retryTimerRef.current);
      retryTimerRef.current = setTimeout(() => {
        setRetryAttempt(nextAttempt);
      }, delay);
      return;
    }
    setImageError(true);
    const rawUri = typeof baseSource === 'object' && baseSource && 'uri' in baseSource ? baseSource.uri : undefined;
    captureEvent('infographic_load_failed', {
      card_id: cardId,
      uri: typeof rawUri === 'string' ? rawUri : 'bundled',
      error: String((err as { error?: unknown })?.error ?? err),
      attempts: retryAttempt + 1,
      had_lottie_fallback: !!lottieSource,
      platform: Platform.OS,
    });
  }, [cardId, baseSource, retryAttempt, lottieSource]);

  const reducedMotion = useReducedMotion();

  const zoomScale = useSharedValue(1);
  const zoomX = useSharedValue(0);
  const zoomY = useSharedValue(0);
  const prevStepRef = useRef<number | undefined>(undefined);

  // Idle "breathing" — subtle pulse + drift that runs continuously.
  // Composes multiplicatively/additively with zoom so dive transitions stay clean.
  const breathScale = useSharedValue(1);
  const breathDriftY = useSharedValue(0);

  // Loading shimmer — a gentle opacity pulse on the skeleton placeholder so a
  // slow/retrying infographic reads as "loading" rather than a broken blank.
  const shimmer = useSharedValue(0.45);

  useEffect(() => {
    let targetX = 0, targetY = 0, targetScale = 1;
    if (zoomRegions) {
      if (typeof diveStep === 'number' && zoomRegions[diveStep]) {
        [targetX, targetY, targetScale] = zoomRegions[diveStep];
      } else if (zoomRegions[0]) {
        [targetX, targetY, targetScale] = zoomRegions[0];
      }
    }
    const prevStep = prevStepRef.current;
    const prevRegion = zoomRegions && typeof prevStep === 'number' ? zoomRegions[prevStep] : undefined;
    const passThroughNeutral =
      typeof diveStep === 'number' &&
      prevStep !== diveStep &&
      !!prevRegion &&
      prevRegion[2] > 1 &&
      targetScale > 1;
    if (passThroughNeutral) {
      const out = { duration: 300 };
      const inn = { duration: 500 };
      zoomScale.value = withSequence(withTiming(1, out), withTiming(targetScale, inn));
      zoomX.value = withSequence(withTiming(0, out), withTiming(targetX, inn));
      zoomY.value = withSequence(withTiming(0, out), withTiming(targetY, inn));
    } else {
      const cfg = { duration: typeof diveStep === 'number' ? 600 : 0 }; // instant if no dive step (initial mount in feed)
      zoomScale.value = withTiming(targetScale, cfg);
      zoomX.value = withTiming(targetX, cfg);
      zoomY.value = withTiming(targetY, cfg);
    }
    prevStepRef.current = diveStep;
  }, [diveStep, zoomRegions, zoomScale, zoomX, zoomY]);

  useEffect(() => {
    if (reducedMotion) {
      breathScale.value = 1;
      breathDriftY.value = 0;
      return;
    }
    breathScale.value = withRepeat(
      withTiming(1.012, { duration: 3200, easing: Easing.inOut(Easing.sin) }),
      -1,
      true,
    );
    breathDriftY.value = withRepeat(
      withTiming(2, { duration: 4800, easing: Easing.inOut(Easing.sin) }),
      -1,
      true,
    );
  }, [breathScale, breathDriftY, reducedMotion]);

  useEffect(() => {
    if (reducedMotion) {
      shimmer.value = 0.85;
      return;
    }
    shimmer.value = withRepeat(
      withTiming(0.85, { duration: 900, easing: Easing.inOut(Easing.sin) }),
      -1,
      true,
    );
  }, [shimmer, reducedMotion]);

  const shimmerStyle = useAnimatedStyle(() => ({ opacity: shimmer.value }));

  const zoomStyle = useAnimatedStyle(() => ({
    transform: [
      { translateX: zoomX.value },
      { translateY: zoomY.value + breathDriftY.value },
      { scale: zoomScale.value * breathScale.value },
    ],
  }));

  // Text overlays patch typos in the static PNG. They're visible in the normal
  // (unzoomed) card view, then fade out the moment dive-mode zoom begins so they
  // don't stick around as a stray rectangle while the image moves underneath.
  // interp [1, 1.1] -> [1, 0] = gone by the time zoom hits 10% (well within the
  // 600ms dive transition).
  const overlayFadeStyle = useAnimatedStyle(() => ({
    opacity: interpolate(zoomScale.value, [1, 1.1], [1, 0], Extrapolation.CLAMP),
  }));

  if (!baseSource && !lottieSource && !finnTapSource) return null;

  return (
    <View>
      {/* Tappable Finn portrait, tap to open full-screen, tap to dismiss */}
      {finnTapSource && (
        <>
          <Pressable onPress={() => setFinnFullscreen(true)} style={s.finnTapThumb}>
            <ExpoImage source={finnTapSource} accessible={false} style={s.finnTapImage} contentFit="cover" cachePolicy="memory-disk" transition={150} />
          </Pressable>
          <Modal visible={finnFullscreen} transparent animationType="fade" statusBarTranslucent>
            <Pressable onPress={() => setFinnFullscreen(false)} style={s.finnModal}>
              <ExpoImage source={finnTapSource} accessible={false} style={s.finnModalImage} contentFit="cover" cachePolicy="memory-disk" transition={150} />
            </Pressable>
          </Modal>
        </>
      )}
      {/* Lottie shows when (a) there's no remote source at all, OR (b) the
          remote source exhausted its retry budget — Lottie is a better
          fallback than nothing for cards that have one configured (e.g. all
          of mod-0-1's fc-0-2-* cards have matching Lottie entries). */}
      {lottieSource && (!baseSource || imageError) && (
        <View style={s.lottieContainer}>
          <LottieView
            source={lottieSource as unknown as AnimationObject}
            autoPlay
            loop
            style={s.lottie}
          />
        </View>
      )}
      {source && imageError && !lottieSource && (
        // No Lottie fallback available — keep the original behavior of hiding
        // the slot entirely. Better than a big gray placeholder. Text + Finn
        // explanation still render. PostHog already logged the failure above.
        null
      )}
      {source && !imageError && (
        <View style={[s.container, isLightBg && s.containerLight, { aspectRatio: ratio ?? 1.2, maxHeight: COMPACT_CARDS.has(cardId) ? 220 : LARGE_CARDS.has(cardId) ? undefined : 270, backgroundColor: '#f1f5f9' }]}>
          {!loaded && (
            <Animated.View pointerEvents="none" style={[StyleSheet.absoluteFill, { backgroundColor: '#e2e8f0' }, shimmerStyle]} />
          )}
          <AnimatedExpoImage key={`img-${cardId}-${retryAttempt}`} source={source} style={[s.image, zoomStyle]} contentFit={COVER_CARDS.has(cardId) ? "cover" : "contain"} cachePolicy="memory-disk" priority="high" transition={200} onLoad={Platform.OS === 'web' ? undefined : handleLoad} onError={handleImageError} />
          {TEXT_OVERLAYS[cardId]?.map((o, i) => (
            <Animated.View
              key={i}
              pointerEvents="none"
              style={[
                {
                  position: "absolute",
                  top: `${o.topPct}%`,
                  left: `${o.leftPct}%`,
                  width: `${o.widthPct}%`,
                  height: `${o.heightPct}%`,
                  backgroundColor: o.backgroundColor ?? "#ffffff",
                  justifyContent: "center",
                  alignItems: "center",
                },
                overlayFadeStyle,
              ]}
            >
              {o.text ? (
                <Text style={{
                  fontSize: o.fontSize ?? 18,
                  fontWeight: "800",
                  color: o.color ?? "#0f172a",
                  textAlign: "center",
                  writingDirection: "rtl",
                }}>{o.text}</Text>
              ) : null}
            </Animated.View>
          ))}
          {lottieSource && (
            <View style={s.lottieFloatingBadge}>
              <LottieView
                source={lottieSource as unknown as AnimationObject}
                autoPlay
                loop
                style={s.lottieSmall}
              />
            </View>
          )}
        </View>
      )}
    </View>
  );
}

const s = StyleSheet.create({
  container: {
    borderRadius: 16,
    overflow: "hidden",
    marginTop: 12,
    marginHorizontal: 8,
    alignSelf: "center",
    backgroundColor: "#ffffff",
  },
  containerLight: {
    backgroundColor: "#f0f4f8",
  },
  image: {
    width: "100%",
    height: "100%",
  },
  finnContainer: {
    borderRadius: 16,
    overflow: "hidden" as const,
    marginTop: 12,
    aspectRatio: 1,
    backgroundColor: "#0c1929",
  },
  finnImage: {
    width: "100%",
    height: "100%",
  },
  lottieContainer: {
    borderRadius: 16,
    overflow: "hidden",
    marginTop: 12,
    aspectRatio: 1.5,
    backgroundColor: "#fefefe",
    justifyContent: "center",
    alignItems: "center",
    borderWidth: 1,
    borderColor: "#f0f0f0",
  },
  lottie: {
    width: "80%",
    height: "80%",
  },
  lottieFloatingBadge: {
    position: "absolute",
    bottom: 8,
    right: 8,
    width: 64,
    height: 64,
    borderRadius: 32,
    backgroundColor: "rgba(255, 255, 255, 0.95)",
    justifyContent: "center",
    alignItems: "center",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 4,
    elevation: 8,
  },
  lottieSmall: {
    width: "80%",
    height: "80%",
  },
  finnTapThumb: {
    borderRadius: 16,
    overflow: "hidden" as const,
    marginTop: 12,
    aspectRatio: 0.7,
    backgroundColor: "#0c1929",
  },
  finnTapImage: {
    width: "100%",
    height: "100%",
  },
  finnModal: {
    flex: 1,
    backgroundColor: "rgba(0,0,0,0.9)",
    justifyContent: "center" as const,
    alignItems: "center" as const,
  },
  finnModalImage: {
    width: "100%",
    height: "90%",
  },
});
