import React, { useCallback, useEffect, useState } from 'react';
import { Image as ExpoImage } from 'expo-image';
import { Modal, Pressable, StyleSheet, Text, View } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import { createAudioPlayer, type AudioPlayer } from 'expo-audio';
import Animated, {
  FadeIn,
  FadeInDown,
  FadeInUp,
  useAnimatedStyle,
  useReducedMotion,
  useSharedValue,
  withRepeat,
  withTiming,
} from 'react-native-reanimated';
import { ChevronLeft, X } from 'lucide-react-native';
import { FINN_HELLO } from '../../retention-loops/finnMascotConfig';
import { tapHaptic, successHaptic } from '../../../utils/haptics';
import { useTutorialStore } from '../../../stores/useTutorialStore';
import type { ToolKey } from '../toolsRegistry';
import type { ToolTutorialStep } from '../data/toolTutorials';

interface Props {
  toolKey: ToolKey;
  steps: ToolTutorialStep[];
}

function FinnPulse() {
  const reducedMotion = useReducedMotion();
  const pulse = useSharedValue(1);
  useEffect(() => {
    if (reducedMotion) return;
    pulse.value = withRepeat(withTiming(1.25, { duration: 1800 }), -1, true);
  }, [reducedMotion, pulse]);
  const animStyle = useAnimatedStyle(() => ({
    transform: [{ scale: pulse.value }],
    opacity: 2 - pulse.value,
  }));
  return <Animated.View style={[s.finnGlow, animStyle]} />;
}

/**
 * First-visit Captain Shark overlay for a single financial tool.
 *
 * Mounts via ToolHeader when the user has never seen this tool's tutorial.
 * Auto-plays bundled Liam-V3 voice-over per step (generated by
 * `scripts/generate-tool-tutorial-audio.mjs`). Last step → marks seen +
 * closes. Top-right X dismisses anytime and also marks seen, so a user who
 * skips it doesn't keep getting interrupted.
 *
 * Mirrors the visual language of the main AppWalkthroughOverlay (Finn
 * mascot floating above a light-blue card, step counter pill, animated
 * dots, RTL) — kept intentionally consistent so users recognize the
 * "tutorial moment" without re-learning the UI.
 */
export function ToolTutorialOverlay({ toolKey, steps }: Props): React.ReactElement | null {
  const markSeen = useTutorialStore((s) => s.markToolTutorialSeen);
  const reducedMotion = useReducedMotion();
  const [step, setStep] = useState(0);
  const [contentKey, setContentKey] = useState(0);
  const [visible, setVisible] = useState(true);

  const stepConfig = steps[step] ?? null;
  const isLast = step >= steps.length - 1;
  const stepAudio = stepConfig?.audio;

  // Auto-play step audio; cleanly stop + dispose on step change / unmount.
  useEffect(() => {
    if (!visible || stepAudio == null) return;
    let playerObj: AudioPlayer | null = null;
    try {
      const player = createAudioPlayer(stepAudio);
      player.play();
      playerObj = player;
    } catch {
      /* silent — audio is enhancement, not blocker */
    }
    return () => {
      if (playerObj) {
        try {
          playerObj.pause();
          playerObj.remove();
        } catch {
          /* ignore */
        }
      }
    };
  }, [stepAudio, visible]);

  const close = useCallback(() => {
    setVisible(false);
    markSeen(toolKey);
  }, [markSeen, toolKey]);

  const handleNext = useCallback(() => {
    try {
      tapHaptic();
    } catch {
      /* haptics best-effort */
    }
    if (isLast) {
      try {
        successHaptic();
      } catch {
        /* ignore */
      }
      close();
      return;
    }
    setStep((s) => s + 1);
    setContentKey((k) => k + 1);
  }, [isLast, close]);

  const handleSkip = useCallback(() => {
    try {
      tapHaptic();
    } catch {
      /* ignore */
    }
    close();
  }, [close]);

  if (!visible || !stepConfig) return null;

  const enterAnim = reducedMotion ? undefined : FadeIn.duration(280);

  return (
    <Modal
      visible
      transparent
      animationType="none"
      statusBarTranslucent
      accessibilityViewIsModal
      onRequestClose={close}
    >
      <View style={s.overlay}>
        {/* ── Top: title pill + X dismiss ── */}
        <SafeAreaView edges={['top']} style={s.topRow}>
          <Animated.View
            key={`pill-${contentKey}`}
            entering={reducedMotion ? undefined : FadeInDown.duration(350)}
            style={s.titlePill}
          >
            {stepConfig.emoji ? <Text style={s.titleEmoji}>{stepConfig.emoji}</Text> : null}
            <Text style={s.titleText} accessibilityRole="header">
              {stepConfig.title}
            </Text>
            <View style={s.stepCounter}>
              <Text style={s.stepCounterText}>{`${step + 1}/${steps.length}`}</Text>
            </View>
          </Animated.View>
          <Pressable
            onPress={handleSkip}
            style={s.dismissBtn}
            hitSlop={12}
            accessibilityRole="button"
            accessibilityLabel="סגירת ההדרכה"
          >
            <X size={20} color="#0c4a6e" strokeWidth={2.6} />
          </Pressable>
        </SafeAreaView>

        {/* Tap-through area so the real screen below is visible (but not
            interactive while overlay is up). */}
        <View style={{ flex: 1 }} />

        {/* ── Bottom: Finn card + CTA ── */}
        <SafeAreaView edges={['bottom']} style={{ paddingHorizontal: 16 }}>
          <Animated.View
            entering={reducedMotion ? undefined : FadeInUp.duration(500)}
            style={s.card}
          >
            <View style={s.glowBorder} />

            <View style={s.finnWrap}>
              <FinnPulse />
              <ExpoImage source={FINN_HELLO} style={s.finn} contentFit="contain" accessible={false} />
            </View>

            <Animated.Text key={`msg-${contentKey}`} entering={enterAnim} style={s.message}>
              {stepConfig.message}
            </Animated.Text>

            <View
              style={s.dotsRow}
              accessibilityLabel={`שלב ${step + 1} מתוך ${steps.length}`}
              accessibilityRole="text"
            >
              {steps.map((_, i) => (
                <View key={i} style={[s.dot, i === step && s.dotActive]} />
              ))}
            </View>

            <Pressable
              onPress={handleNext}
              style={s.ctaBtn}
              accessibilityRole="button"
              accessibilityLabel={isLast ? 'סיום ההדרכה' : 'המשך לשלב הבא'}
            >
              <Text style={s.ctaText}>{isLast ? 'סיימתי' : 'המשך'}</Text>
              {!isLast ? <ChevronLeft size={20} color="#ffffff" /> : null}
            </Pressable>
          </Animated.View>
        </SafeAreaView>
      </View>
    </Modal>
  );
}

const CARD_RADIUS = 28;

const s = StyleSheet.create({
  overlay: {
    flex: 1,
    backgroundColor: 'rgba(10, 22, 40, 0.18)',
  },
  topRow: {
    flexDirection: 'row-reverse',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 16,
    paddingTop: 36,
    gap: 10,
  },
  titlePill: {
    flexDirection: 'row-reverse',
    alignItems: 'center',
    gap: 8,
    backgroundColor: 'rgba(255,255,255,0.97)',
    borderRadius: 999,
    paddingHorizontal: 18,
    paddingVertical: 9,
    shadowColor: '#0ea5e9',
    shadowOpacity: 0.3,
    shadowRadius: 20,
    shadowOffset: { width: 0, height: 4 },
    elevation: 10,
  },
  titleEmoji: { fontSize: 20 },
  titleText: {
    fontSize: 15,
    fontWeight: '900',
    color: '#0c4a6e',
    writingDirection: 'rtl',
  },
  stepCounter: {
    backgroundColor: '#e0f2fe',
    borderRadius: 10,
    paddingHorizontal: 7,
    paddingVertical: 2,
    marginStart: 4,
  },
  stepCounterText: {
    fontSize: 11,
    fontWeight: '800',
    color: '#0284c7',
  },
  dismissBtn: {
    width: 36,
    height: 36,
    borderRadius: 999,
    backgroundColor: 'rgba(255,255,255,0.95)',
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: '#0ea5e9',
    shadowOpacity: 0.2,
    shadowRadius: 6,
    shadowOffset: { width: 0, height: 2 },
    elevation: 4,
  },
  card: {
    backgroundColor: '#e0f2fe',
    borderRadius: CARD_RADIUS,
    paddingHorizontal: 22,
    paddingTop: 52,
    paddingBottom: 20,
    marginBottom: 10,
    alignItems: 'center',
    shadowColor: '#0ea5e9',
    shadowOpacity: 0.3,
    shadowRadius: 24,
    shadowOffset: { width: 0, height: -4 },
    elevation: 14,
    overflow: 'visible',
  },
  glowBorder: {
    position: 'absolute',
    top: -1,
    left: -1,
    right: -1,
    bottom: -1,
    borderRadius: CARD_RADIUS + 1,
    borderWidth: 1.5,
    borderColor: 'rgba(14, 165, 233, 0.35)',
  },
  finnWrap: {
    position: 'absolute',
    top: -36,
    alignItems: 'center',
    justifyContent: 'center',
  },
  finnGlow: {
    position: 'absolute',
    width: 80,
    height: 80,
    borderRadius: 40,
    backgroundColor: 'rgba(56, 189, 248, 0.25)',
  },
  finn: { width: 68, height: 68 },
  message: {
    fontSize: 15,
    fontWeight: '600',
    color: '#0c4a6e',
    lineHeight: 24,
    writingDirection: 'rtl',
    textAlign: 'center',
    marginBottom: 16,
  },
  dotsRow: {
    flexDirection: 'row-reverse',
    justifyContent: 'center',
    gap: 5,
    marginBottom: 18,
  },
  dot: {
    width: 6,
    height: 6,
    borderRadius: 3,
    backgroundColor: '#bae6fd',
  },
  dotActive: {
    backgroundColor: '#38bdf8',
    width: 18,
    borderRadius: 3,
  },
  ctaBtn: {
    width: '100%',
    height: 52,
    backgroundColor: '#38bdf8',
    borderRadius: 16,
    alignItems: 'center',
    justifyContent: 'center',
    flexDirection: 'row-reverse',
    gap: 6,
    borderBottomWidth: 4,
    borderBottomColor: '#0ea5e9',
    shadowColor: '#38bdf8',
    shadowOpacity: 0.4,
    shadowRadius: 10,
    shadowOffset: { width: 0, height: 3 },
    elevation: 6,
  },
  ctaText: {
    color: '#ffffff',
    fontSize: 17,
    fontWeight: '900',
  },
});
