import React, { useCallback, useEffect, useState } from 'react';
import { Image as ExpoImage } from 'expo-image';
import { Platform, Pressable, StyleSheet, Text, View } from 'react-native';
import { SafeAreaView, useSafeAreaInsets } from 'react-native-safe-area-context';
import { createAudioPlayer, type AudioPlayer } from 'expo-audio';
import Animated, {
  FadeIn,
  FadeInDown,
  FadeInUp,
  useReducedMotion,
} from 'react-native-reanimated';
import { ChevronLeft, X } from 'lucide-react-native';
import { FINN_HELLO } from '../../retention-loops/finnMascotConfig';
import { tapHaptic, successHaptic } from '../../../utils/haptics';
import { useTutorialStore } from '../../../stores/useTutorialStore';
import type { ToolKey } from '../toolsRegistry';
import type { ToolTutorialStep } from '../data/toolTutorials';

interface Props {
  /** Tool hosts: marks `hasSeenToolTutorial[toolKey]` on close. */
  toolKey?: ToolKey;
  steps: ToolTutorialStep[];
  /** Non-tool hosts (e.g. the friends hub) persist their own seen-flag here.
   *  Receives whether the user finished all steps (false = X-dismissed). */
  onSeen?: (completed: boolean) => void;
}

// Static glow — pulsing animation removed (אודרי restraint: with the dot row
// + voice-over already carrying the rhythm, the glow doesn't need a third
// channel of attention).
function FinnPulse() {
  return <View style={s.finnGlow} />;
}

/**
 * First-visit Captain Shark overlay for a single financial tool.
 *
 * Mounts via ToolHeader when the user has never seen this tool's tutorial.
 * Auto-plays bundled Liam-V3 voice-over per step (generated by
 * `scripts/generate-tool-tutorial-audio.mjs`). Last step → marks seen +
 * closes. Top-right X dismisses anytime and also marks seen, so a user who
 * skips it doesn't keep getting interrupted.
 *
 * Mirrors the visual language of the main AppWalkthroughOverlay (Finn
 * mascot floating above a light-blue card, step counter pill, animated
 * dots, RTL) — kept intentionally consistent so users recognize the
 * "tutorial moment" without re-learning the UI.
 */
export function ToolTutorialOverlay({ toolKey, steps, onSeen }: Props): React.ReactElement | null {
  const markSeen = useTutorialStore((s) => s.markToolTutorialSeen);
  const reducedMotion = useReducedMotion();
  const insets = useSafeAreaInsets();
  const [step, setStep] = useState(0);
  const [contentKey, setContentKey] = useState(0);
  const [visible, setVisible] = useState(true);

  const stepConfig = steps[step] ?? null;
  const isLast = step >= steps.length - 1;
  const stepAudioUrl = stepConfig?.audioUrl;

  // Auto-play step audio; cleanly stop + dispose on step change / unmount.
  useEffect(() => {
    if (!visible || !stepAudioUrl) return;
    let playerObj: AudioPlayer | null = null;
    try {
      const player = createAudioPlayer({ uri: stepAudioUrl });
      player.play();
      playerObj = player;
    } catch {
      /* silent — audio is enhancement, not blocker */
    }
    return () => {
      if (playerObj) {
        try {
          playerObj.pause();
          playerObj.remove();
        } catch {
          /* ignore */
        }
      }
    };
  }, [stepAudioUrl, visible]);

  const close = useCallback(
    (completed: boolean) => {
      setVisible(false);
      if (toolKey) markSeen(toolKey);
      onSeen?.(completed);
    },
    [markSeen, toolKey, onSeen],
  );

  const handleNext = useCallback(() => {
    try {
      tapHaptic();
    } catch {
      /* haptics best-effort */
    }
    if (isLast) {
      try {
        successHaptic();
      } catch {
        /* ignore */
      }
      close(true);
      return;
    }
    setStep((s) => s + 1);
    setContentKey((k) => k + 1);
  }, [isLast, close]);

  const handleSkip = useCallback(() => {
    try {
      tapHaptic();
    } catch {
      /* ignore */
    }
    close(false);
  }, [close]);

  if (!visible || !stepConfig) return null;

  const enterAnim = reducedMotion ? undefined : FadeIn.duration(280);

  return (
    // Absolutely-positioned overlay (no <Modal>) — Modal on iOS leaves the
    // host view's touch handling tangled after dismissal so the tool buttons
    // beneath stay unresponsive. Mounting as an absolute sibling cleans up
    // touches the moment ToolTutorialMount sees `hasSeen=true` and returns
    // null. Same pattern as TickerPickerSheet.
    <View
      style={s.overlay}
      accessibilityViewIsModal
      pointerEvents="box-none"
    >
      {/* Dimmed backdrop — covers the screen but doesn't capture taps so the
          press already handled by inner Pressables flows correctly. */}
      <View style={s.backdrop} pointerEvents="none" />

      {/* ── Top: title pill CENTERED + X dismiss top-right ── */}
      <SafeAreaView edges={['top']} style={s.topArea}>
        <Animated.View
          key={`pill-${contentKey}`}
          entering={reducedMotion ? undefined : FadeInDown.duration(350)}
          style={s.titlePill}
        >
          {stepConfig.emoji ? <Text style={s.titleEmoji}>{stepConfig.emoji}</Text> : null}
          <Text style={s.titleText} accessibilityRole="header">
            {stepConfig.title}
          </Text>
          <View style={s.stepCounter}>
            <Text style={s.stepCounterText}>{`${step + 1}/${steps.length}`}</Text>
          </View>
        </Animated.View>
        <Pressable
          onPress={handleSkip}
          style={[s.dismissBtn, { top: insets.top + 72 }]}
          hitSlop={12}
          accessibilityRole="button"
          accessibilityLabel="סגירת ההדרכה"
        >
          <X size={20} color="#0c4a6e" strokeWidth={2.6} />
        </Pressable>
      </SafeAreaView>

      {/* Middle is intentionally empty + pointer-events: none so the real
          screen below stays visible AND uninteractive while the overlay
          is up. */}

      {/* ── Bottom: Finn card + CTA ── */}
      <SafeAreaView edges={['bottom']} style={s.bottomArea}>
        <Animated.View
          entering={reducedMotion ? undefined : FadeInUp.duration(500)}
          style={s.card}
        >
          <View style={s.glowBorder} />

          <View style={s.finnWrap}>
            <FinnPulse />
            <ExpoImage source={FINN_HELLO} style={s.finn} contentFit="contain" accessible={false} />
          </View>

          <Animated.Text key={`msg-${contentKey}`} entering={enterAnim} style={s.message}>
            {stepConfig.message}
          </Animated.Text>

          <View
            style={s.dotsRow}
            accessibilityLabel={`שלב ${step + 1} מתוך ${steps.length}`}
            accessibilityRole="text"
          >
            {steps.map((_, i) => (
              <View key={i} style={[s.dot, i === step && s.dotActive]} />
            ))}
          </View>

          <Pressable
            onPress={handleNext}
            style={s.ctaBtn}
            accessibilityRole="button"
            accessibilityLabel={isLast ? 'סיום ההדרכה' : 'המשך לשלב הבא'}
          >
            <Text style={s.ctaText}>{isLast ? 'סיימתי' : 'המשך'}</Text>
            {!isLast ? <ChevronLeft size={20} color="#ffffff" /> : null}
          </Pressable>
        </Animated.View>
      </SafeAreaView>
    </View>
  );
}

const CARD_RADIUS = 28;

const s = StyleSheet.create({
  overlay: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    zIndex: 1000,
    // RN-Web stable fixed positioning so the overlay stays put on scroll.
    ...(Platform.OS === 'web' ? { position: 'fixed' as 'absolute' } : {}),
  },
  backdrop: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: 'rgba(10, 22, 40, 0.18)',
  },
  topArea: {
    // Centered title pill + absolute-positioned X (top-right). Pill itself
    // is centered horizontally and pushed slightly lower than the original
    // 36px so it reads as the screen's focal title, not a top-bar element.
    alignItems: 'center',
    justifyContent: 'flex-start',
    paddingTop: 72,
    paddingHorizontal: 16,
    position: 'relative',
  },
  bottomArea: {
    paddingHorizontal: 16,
    // Bottom area sits absolutely at the screen bottom so the middle stays
    // tap-through and the card always hugs the safe-area bottom edge.
    position: 'absolute',
    left: 0,
    right: 0,
    bottom: 0,
  },
  titlePill: {
    flexDirection: 'row-reverse',
    alignItems: 'center',
    gap: 8,
    backgroundColor: 'rgba(255,255,255,0.97)',
    borderRadius: 999,
    paddingHorizontal: 18,
    paddingVertical: 9,
    shadowColor: '#0ea5e9',
    shadowOpacity: 0.3,
    shadowRadius: 20,
    shadowOffset: { width: 0, height: 4 },
    elevation: 10,
  },
  titleEmoji: { fontSize: 20 },
  titleText: {
    fontSize: 15,
    fontWeight: '900',
    color: '#0c4a6e',
    writingDirection: 'rtl',
  },
  stepCounter: {
    backgroundColor: '#e0f2fe',
    borderRadius: 10,
    paddingHorizontal: 7,
    paddingVertical: 2,
    marginStart: 4,
  },
  stepCounterText: {
    fontSize: 11,
    fontWeight: '800',
    color: '#0284c7',
  },
  dismissBtn: {
    // Pinned to the visual top-RIGHT of the screen. In a Hebrew/RTL app the
    // right corner is where users expect close affordances (mirrors LTR's
    // top-left). The `top` is set inline at the render site so it includes
    // the safe-area inset and stays aligned with the centered pill across
    // all iPhones.
    position: 'absolute',
    right: 16,
    width: 36,
    height: 36,
    borderRadius: 999,
    backgroundColor: 'rgba(255,255,255,0.95)',
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: '#0ea5e9',
    shadowOpacity: 0.2,
    shadowRadius: 6,
    shadowOffset: { width: 0, height: 2 },
    elevation: 4,
  },
  card: {
    backgroundColor: '#e0f2fe',
    borderRadius: CARD_RADIUS,
    paddingHorizontal: 22,
    paddingTop: 52,
    paddingBottom: 20,
    marginBottom: 10,
    alignItems: 'center',
    shadowColor: '#0ea5e9',
    shadowOpacity: 0.3,
    shadowRadius: 24,
    shadowOffset: { width: 0, height: -4 },
    elevation: 14,
    overflow: 'visible',
  },
  glowBorder: {
    position: 'absolute',
    top: -1,
    left: -1,
    right: -1,
    bottom: -1,
    borderRadius: CARD_RADIUS + 1,
    borderWidth: 1.5,
    borderColor: 'rgba(14, 165, 233, 0.35)',
  },
  finnWrap: {
    position: 'absolute',
    top: -36,
    alignItems: 'center',
    justifyContent: 'center',
  },
  finnGlow: {
    position: 'absolute',
    width: 80,
    height: 80,
    borderRadius: 40,
    backgroundColor: 'rgba(56, 189, 248, 0.25)',
  },
  finn: { width: 68, height: 68 },
  message: {
    fontSize: 15,
    fontWeight: '600',
    color: '#0c4a6e',
    lineHeight: 24,
    writingDirection: 'rtl',
    textAlign: 'center',
    marginBottom: 16,
  },
  dotsRow: {
    flexDirection: 'row-reverse',
    justifyContent: 'center',
    gap: 5,
    marginBottom: 18,
  },
  dot: {
    width: 6,
    height: 6,
    borderRadius: 3,
    backgroundColor: '#bae6fd',
  },
  dotActive: {
    backgroundColor: '#38bdf8',
    width: 18,
    borderRadius: 3,
  },
  ctaBtn: {
    width: '100%',
    height: 52,
    backgroundColor: '#38bdf8',
    borderRadius: 16,
    alignItems: 'center',
    justifyContent: 'center',
    flexDirection: 'row-reverse',
    gap: 6,
    borderBottomWidth: 4,
    borderBottomColor: '#0ea5e9',
    shadowColor: '#38bdf8',
    shadowOpacity: 0.4,
    shadowRadius: 10,
    shadowOffset: { width: 0, height: 3 },
    elevation: 6,
  },
  ctaText: {
    color: '#ffffff',
    fontSize: 17,
    fontWeight: '900',
  },
});
