/**
 * Sound signature for the Daily News Challenge.
 *
 * Two short SFX, bundled as WAV (generated by
 * `node scripts/generate-daily-news-sfx.mjs`):
 *   - success-chord  → plays on a correct chip pick
 *   - chest-swoosh   → plays on a chest open
 *
 * The "soft thud" for wrong answers is intentionally haptic-only — the
 * error haptic + chip shake already convey the miss without adding a
 * shame-y noise. We can layer audio in later if testing wants it.
 */

import { createAudioPlayer, type AudioPlayer } from 'expo-audio';

// SFX are supposed to be generated by `node scripts/generate-daily-news-sfx.mjs`
// (script not yet in this repo) into assets/audio/daily-news/. Until that
// script + assets land, audio is a no-op — the bundle would fail outright
// if Metro tried to resolve the missing require() at build time. Wrapping
// in try/catch doesn't help because require() resolves statically.
//
// When the SFX files exist, uncomment the requires and the players will
// pick them up automatically via the lazy getters below.
const SUCCESS_CHORD: number | null = null;
const CHEST_SWOOSH: number | null = null;

let successPlayer: AudioPlayer | null = null;
let swooshPlayer: AudioPlayer | null = null;

/** Lazily instantiate so module init doesn't touch the audio session on web
 *  where expo-audio degrades gracefully. */
function getSuccessPlayer(): AudioPlayer | null {
  if (successPlayer) return successPlayer;
  if (SUCCESS_CHORD == null) return null;
  try {
    successPlayer = createAudioPlayer(SUCCESS_CHORD);
    successPlayer.volume = 0.8;
    return successPlayer;
  } catch {
    return null;
  }
}

function getSwooshPlayer(): AudioPlayer | null {
  if (swooshPlayer) return swooshPlayer;
  if (CHEST_SWOOSH == null) return null;
  try {
    swooshPlayer = createAudioPlayer(CHEST_SWOOSH);
    swooshPlayer.volume = 0.85;
    return swooshPlayer;
  } catch {
    return null;
  }
}

export async function playSuccessChord(): Promise<void> {
  const p = getSuccessPlayer();
  if (!p) return;
  try {
    p.seekTo(0);
    p.play();
  } catch {
    // expo-audio throws on web/Expo Go without permission — ignore.
  }
}

/** Reserved — currently a no-op so callers don't need a separate guard.
 *  Haptic + chip shake already convey the wrong-answer feedback. */
export async function playSoftThud(): Promise<void> {
  // intentionally empty
}

export async function playChestOpenSwoosh(): Promise<void> {
  const p = getSwooshPlayer();
  if (!p) return;
  try {
    p.seekTo(0);
    p.play();
  } catch {
    // see above
  }
}
