/**
 * Sound signature for the Daily News Challenge.
 *
 * Two short SFX, bundled as WAV (generated by
 * `node scripts/generate-daily-news-sfx.mjs`):
 *   - success-chord  → plays on a correct chip pick
 *   - chest-swoosh   → plays on a chest open
 *
 * The "soft thud" for wrong answers is intentionally haptic-only — the
 * error haptic + chip shake already convey the miss without adding a
 * shame-y noise. We can layer audio in later if testing wants it.
 */

import { createAudioPlayer, type AudioPlayer } from 'expo-audio';

// Pre-load the assets at module load so the first play has zero latency.
// require() returns a number (asset id) that expo-audio accepts directly.
const SUCCESS_CHORD = require('../../../../assets/audio/daily-news/success-chord.wav');
const CHEST_SWOOSH = require('../../../../assets/audio/daily-news/chest-swoosh.wav');

let successPlayer: AudioPlayer | null = null;
let swooshPlayer: AudioPlayer | null = null;

/** Lazily instantiate so module init doesn't touch the audio session on web
 *  where expo-audio degrades gracefully. */
function getSuccessPlayer(): AudioPlayer | null {
  if (successPlayer) return successPlayer;
  try {
    successPlayer = createAudioPlayer(SUCCESS_CHORD);
    successPlayer.volume = 0.8;
    return successPlayer;
  } catch {
    return null;
  }
}

function getSwooshPlayer(): AudioPlayer | null {
  if (swooshPlayer) return swooshPlayer;
  try {
    swooshPlayer = createAudioPlayer(CHEST_SWOOSH);
    swooshPlayer.volume = 0.85;
    return swooshPlayer;
  } catch {
    return null;
  }
}

export async function playSuccessChord(): Promise<void> {
  const p = getSuccessPlayer();
  if (!p) return;
  try {
    p.seekTo(0);
    p.play();
  } catch {
    // expo-audio throws on web/Expo Go without permission — ignore.
  }
}

/** Reserved — currently a no-op so callers don't need a separate guard.
 *  Haptic + chip shake already convey the wrong-answer feedback. */
export async function playSoftThud(): Promise<void> {
  // intentionally empty
}

export async function playChestOpenSwoosh(): Promise<void> {
  const p = getSwooshPlayer();
  if (!p) return;
  try {
    p.seekTo(0);
    p.play();
  } catch {
    // see above
  }
}
