import type { DailyConcept } from "./dailyConceptTypes";

// Lottie sources for concepts
const LOTTIE = {
  growth: require("../../../assets/lottie/wired-flat-161-growth-hover-pinch.json"),
  barChart: require("../../../assets/lottie/wired-flat-153-bar-chart-hover-pinch.json"),
  shield: require("../../../assets/lottie/wired-flat-457-shield-security-hover-pinch.json"),
  coins: require("../../../assets/lottie/wired-flat-298-coins-hover-jump.json"),
  balance: require("../../../assets/lottie/wired-flat-402-legal-balance-legal-hover-pinch.json"),
  book: require("../../../assets/lottie/wired-flat-112-book-hover-closed.json"),
  brain: require("../../../assets/lottie/wired-flat-426-brain-hover-pinch.json"),
  star: require("../../../assets/lottie/wired-flat-237-star-rating-hover-pinch.json"),
  home: require("../../../assets/lottie/wired-flat-63-home-hover-3d-roll.json"),
  rocket: require("../../../assets/lottie/wired-flat-489-rocket-space-hover-flying.json"),
  target: require("../../../assets/lottie/wired-flat-458-goal-target-hover-hit.json"),
  building: require("../../../assets/lottie/wired-flat-483-building-hover-blinking.json"),
  crown: require("../../../assets/lottie/wired-flat-407-crown-king-lord-hover-roll.json"),
  fire: require("../../../assets/lottie/wired-flat-2804-fire-flame-hover-pinch.json"),
  coinDollar: require("../../../assets/lottie/wired-flat-291-coin-dollar-hover-pinch.json"),
  lineChart: require("../../../assets/lottie/wired-flat-163-graph-line-chart-hover-slide.json"),
  compass: require("../../../assets/lottie/wired-flat-782-compass-hover-pinch.json"),
  lock: require("../../../assets/lottie/wired-flat-94-lock-unlock-hover-locked.json"),
  bulb: require("../../../assets/lottie/wired-flat-36-bulb-hover-blink.json"),
  trophy: require("../../../assets/lottie/wired-flat-3263-trophy-circle-hover-roll.json"),
  gift: require("../../../assets/lottie/wired-flat-412-gift-hover-squeeze.json"),
  portfolio: require("../../../assets/lottie/wired-flat-1023-portfolio-hover-pinch.json"),
  decrease: require("../../../assets/lottie/wired-flat-162-decrease-hover-pinch.json"),
  clock: require("../../../assets/lottie/wired-flat-45-clock-time-hover-pinch.json"),
  barChartGrowth: require("../../../assets/lottie/wired-flat-152-bar-chart-arrow-hover-growth.json"),
};

export const DAILY_CONCEPTS: DailyConcept[] = [
  // Chapter 1: יסודות
  {
    id: "concept-1",
    titleHe: "ריבית דריבית",
    descriptionHe: "כשהריבית שנצברה מתווספת לקרן ומייצרת ריבית נוספת — כסף שמרוויח כסף. ככל שמתחילים מוקדם יותר, האפקט חזק יותר.",
    lottieSource: LOTTIE.growth,
    chapterId: 1,
  },
  {
    id: "concept-3",
    titleHe: "תקציב 50/30/20",
    descriptionHe: "שיטת תקציב פשוטה: 50% לצרכים בסיסיים, 30% לרצונות, 20% לחיסכון והשקעות.",
    lottieSource: LOTTIE.barChart,
    chapterId: 1,
  },
  {
    id: "concept-4",
    titleHe: "קרן חירום",
    descriptionHe: "כרית ביטחון כלכלית של 3-6 חודשי הוצאות חיים, נגישה מיידית למקרי חירום בלתי צפויים.",
    lottieSource: LOTTIE.shield,
    chapterId: 1,
  },
  {
    id: "concept-13",
    titleHe: "תזרים מזומנים",
    descriptionHe: "ההפרש בין הכנסות להוצאות בתקופה מסוימת. תזרים חיובי = נכנס יותר ממה שיוצא.",
    lottieSource: LOTTIE.coins,
    chapterId: 1,
  },
  {
    id: "concept-15",
    titleHe: "עלות אלטרנטיבית",
    descriptionHe: "מה שאתה מפסיד כשאתה בוחר אפשרות אחת על פני אחרת. כל בחירה כלכלית = ויתור על משהו אחר.",
    lottieSource: LOTTIE.balance,
    chapterId: 1,
  },
  {
    id: "concept-19",
    titleHe: "הוצאות קבועות vs משתנות",
    descriptionHe: "קבועות: שכירות, ביטוח, מנויים. משתנות: אוכל, בילויים, קניות. על המשתנות קל יותר לחסוך.",
    lottieSource: LOTTIE.book,
    chapterId: 1,
  },
  {
    id: "concept-27",
    titleHe: "חיסכון אוטומטי",
    descriptionHe: "הוראת קבע לחיסכון ביום שמקבלים משכורת. \"תשלם לעצמך קודם\" — לפני שמספיקים לבזבז.",
    lottieSource: LOTTIE.clock,
    chapterId: 1,
  },

  // Chapter 2: ביטחון
  {
    id: "concept-9",
    titleHe: "דירוג אשראי",
    descriptionHe: "ציון שמשקף את האמינות הפיננסית שלך. דירוג גבוה = ריבית נמוכה יותר על הלוואות.",
    lottieSource: LOTTIE.star,
    chapterId: 2,
  },
  {
    id: "concept-12",
    titleHe: "קרן פנסיה",
    descriptionHe: "חיסכון ארוך טווח לפרישה. המעסיק והעובד מפרישים יחד, ומקבלים הטבות מס משמעותיות.",
    lottieSource: LOTTIE.trophy,
    chapterId: 2,
  },
  {
    id: "concept-21",
    titleHe: "ביטוח חיים",
    descriptionHe: "מגן כלכלי על המשפחה במקרה מוות. ביטוח ריסק = זול ומכסה תקופה מוגדרת.",
    lottieSource: LOTTIE.shield,
    chapterId: 2,
  },
  {
    id: "concept-23",
    titleHe: "קרן השתלמות",
    descriptionHe: "חיסכון לטווח של 6 שנים עם פטור ממס רווחי הון. אחד מהמכשירים הכי משתלמים בישראל.",
    lottieSource: LOTTIE.gift,
    chapterId: 2,
  },
  {
    id: "concept-26",
    titleHe: "תעריף מס שולי",
    descriptionHe: "אחוז המס על השקל האחרון שהרווחת. בישראל: מדרגות מ-10% ועד 50% על הכנסה גבוהה.",
    lottieSource: LOTTIE.portfolio,
    chapterId: 2,
  },

  // Chapter 3: יציבות
  {
    id: "concept-2",
    titleHe: "אינפלציה",
    descriptionHe: "עליית מחירים כללית שמקטינה את כוח הקנייה של הכסף. 100 ש\"ח היום שווים פחות מ-100 ש\"ח בעוד 10 שנים.",
    lottieSource: LOTTIE.decrease,
    chapterId: 3,
  },
  {
    id: "concept-6",
    titleHe: "מס רווחי הון",
    descriptionHe: "מס של 25% על רווחים ממכירת ניירות ערך, נדל\"ן להשקעה ונכסים פיננסיים אחרים בישראל.",
    lottieSource: LOTTIE.portfolio,
    chapterId: 3,
  },
  {
    id: "concept-8",
    titleHe: "ריבית בנק ישראל",
    descriptionHe: "הריבית שבנק ישראל קובע ומשפיעה על עלות האשראי, תשואת החיסכון, ושער החליפין.",
    lottieSource: LOTTIE.building,
    chapterId: 3,
  },
  {
    id: "concept-20",
    titleHe: "שער חליפין",
    descriptionHe: "היחס בין ערך של שני מטבעות. כשהדולר עולה, יבוא מתייקר וייצוא משתלם יותר.",
    lottieSource: LOTTIE.coinDollar,
    chapterId: 3,
  },
  {
    id: "concept-22",
    titleHe: "ריבית צמודה למדד",
    descriptionHe: "ריבית שמתעדכנת לפי מדד המחירים לצרכן — שומרת על ערך הכסף גם בתקופות אינפלציה.",
    lottieSource: LOTTIE.lineChart,
    chapterId: 3,
  },
  {
    id: "concept-29",
    titleHe: "עמלות נסתרות",
    descriptionHe: "דמי ניהול, עמלות קנייה/מכירה, דמי משמרת — הכל מכרסם בתשואה. חשוב להשוות לפני שבוחרים.",
    lottieSource: LOTTIE.bulb,
    chapterId: 3,
  },

  // Chapter 4: צמיחה
  {
    id: "concept-5",
    titleHe: "מדד S&P 500",
    descriptionHe: "מדד של 500 החברות הגדולות בארה\"ב. השקעה במדד מאפשרת פיזור רחב בקנייה אחת.",
    lottieSource: LOTTIE.barChartGrowth,
    chapterId: 4,
  },
  {
    id: "concept-7",
    titleHe: "ETF — קרן סל",
    descriptionHe: "קרן שנסחרת בבורסה ועוקבת אחרי מדד. דרך זולה ופשוטה להשקיע בשוק ההון עם פיזור מובנה.",
    lottieSource: LOTTIE.portfolio,
    chapterId: 4,
  },
  {
    id: "concept-10",
    titleHe: "תשואה שנתית",
    descriptionHe: "אחוז הרווח או ההפסד על השקעה במהלך שנה. תשואה ממוצעת של S&P 500: כ-10% בשנה.",
    lottieSource: LOTTIE.growth,
    chapterId: 4,
  },
  {
    id: "concept-11",
    titleHe: "פיזור סיכונים",
    descriptionHe: "אל תשים את כל הביצים בסל אחד — פיזור בין סוגי נכסים שונים מקטין את הסיכון הכולל.",
    lottieSource: LOTTIE.compass,
    chapterId: 4,
  },
  {
    id: "concept-16",
    titleHe: "מניה",
    descriptionHe: "חלק בבעלות על חברה. כשהחברה מצליחה, ערך המניה עולה ואתה מרוויח.",
    lottieSource: LOTTIE.barChart,
    chapterId: 4,
  },
  {
    id: "concept-17",
    titleHe: "אגרת חוב",
    descriptionHe: "הלוואה שאתה נותן לממשלה או לחברה. בתמורה מקבלים ריבית קבועה — פחות סיכון מהשקעה במניות.",
    lottieSource: LOTTIE.lock,
    chapterId: 4,
  },
  {
    id: "concept-18",
    titleHe: "דיבידנד",
    descriptionHe: "חלוקת רווחים של חברה לבעלי המניות שלה. הכנסה פסיבית שמתקבלת בלי למכור את המניה.",
    lottieSource: LOTTIE.coinDollar,
    chapterId: 4,
  },

  // Chapter 5: חופש כלכלי
  {
    id: "concept-14",
    titleHe: "ריבית נומינלית vs ריאלית",
    descriptionHe: "ריבית נומינלית = הריבית המוצהרת. ריבית ריאלית = אחרי הפחתת אינפלציה. זה מה שבאמת משנה.",
    lottieSource: LOTTIE.brain,
    chapterId: 5,
  },
  {
    id: "concept-24",
    titleHe: "מינוף פיננסי",
    descriptionHe: "שימוש בכסף שאול כדי להגדיל השקעה. מגביר רווחים — אבל גם הפסדים. סיכון גבוה.",
    lottieSource: LOTTIE.rocket,
    chapterId: 5,
  },
  {
    id: "concept-25",
    titleHe: "נדל\"ן מניב",
    descriptionHe: "נכס שמייצר הכנסה שוטפת מדמי שכירות. דורש הון התחלתי גבוה אבל נחשב יציב יחסית.",
    lottieSource: LOTTIE.home,
    chapterId: 5,
  },
  {
    id: "concept-28",
    titleHe: "כלל ה-72",
    descriptionHe: "מחלקים 72 בתשואה השנתית = שנים להכפלת הכסף. למשל: ב-8% תשואה, הכסף מוכפל תוך 9 שנים.",
    lottieSource: LOTTIE.target,
    chapterId: 5,
  },
  {
    id: "concept-30",
    titleHe: "FIRE — עצמאות כלכלית",
    descriptionHe: "Financial Independence, Retire Early. חסוך 50%+ מההכנסה, השקע, ופרוש מוקדם מהעבודה.",
    lottieSource: LOTTIE.fire,
    chapterId: 5,
  },
];
