import type { DailyConcept } from "./dailyConceptTypes";

// Lottie sources for concepts
const LOTTIE = {
  growth: require("../../../assets/lottie/wired-flat-161-growth-hover-pinch.json"),
  barChart: require("../../../assets/lottie/wired-flat-153-bar-chart-hover-pinch.json"),
  shield: require("../../../assets/lottie/wired-flat-457-shield-security-hover-pinch.json"),
  coins: require("../../../assets/lottie/wired-flat-298-coins-hover-jump.json"),
  balance: require("../../../assets/lottie/wired-flat-402-legal-balance-legal-hover-pinch.json"),
  book: require("../../../assets/lottie/wired-flat-112-book-hover-closed.json"),
  brain: require("../../../assets/lottie/wired-flat-426-brain-hover-pinch.json"),
  star: require("../../../assets/lottie/wired-flat-237-star-rating-hover-pinch.json"),
  home: require("../../../assets/lottie/wired-flat-63-home-hover-3d-roll.json"),
  rocket: require("../../../assets/lottie/wired-flat-489-rocket-space-hover-flying.json"),
  target: require("../../../assets/lottie/wired-flat-458-goal-target-hover-hit.json"),
  building: require("../../../assets/lottie/wired-flat-483-building-hover-blinking.json"),
  crown: require("../../../assets/lottie/wired-flat-407-crown-king-lord-hover-roll.json"),
  fire: require("../../../assets/lottie/wired-flat-2804-fire-flame-hover-pinch.json"),
  coinDollar: require("../../../assets/lottie/wired-flat-291-coin-dollar-hover-pinch.json"),
  lineChart: require("../../../assets/lottie/wired-flat-163-graph-line-chart-hover-slide.json"),
  compass: require("../../../assets/lottie/wired-flat-782-compass-hover-pinch.json"),
  lock: require("../../../assets/lottie/wired-flat-94-lock-unlock-hover-locked.json"),
  bulb: require("../../../assets/lottie/wired-flat-36-bulb-hover-blink.json"),
  trophy: require("../../../assets/lottie/wired-flat-3263-trophy-circle-hover-roll.json"),
  gift: require("../../../assets/lottie/wired-flat-412-gift-hover-squeeze.json"),
  portfolio: require("../../../assets/lottie/wired-flat-1023-portfolio-hover-pinch.json"),
  decrease: require("../../../assets/lottie/wired-flat-162-decrease-hover-pinch.json"),
  clock: require("../../../assets/lottie/wired-flat-45-clock-time-hover-pinch.json"),
  barChartGrowth: require("../../../assets/lottie/wired-flat-152-bar-chart-arrow-hover-growth.json"),
};

export const DAILY_CONCEPTS: DailyConcept[] = [
  // Chapter 1: יסודות
  {
    id: "concept-1",
    titleHe: "ריבית דריבית",
    descriptionHe: "כשהריבית שנצברה מתווספת לקרן ומייצרת ריבית נוספת, כסף שמרוויח כסף. ככל שמתחילים מוקדם יותר, האפקט חזק יותר.",
    lottieSource: LOTTIE.growth,
    chapterId: 1,
  },
  {
    id: "concept-3",
    titleHe: "תקציב 50/30/20",
    descriptionHe: "שיטת תקציב פשוטה: 50% לצרכים, 30% לרצונות, 20% לחיסכון. נקודת מוצא — התאם לעלות הדיור באזורך.",
    lottieSource: LOTTIE.barChart,
    chapterId: 1,
  },
  {
    id: "concept-4",
    titleHe: "קרן חירום",
    descriptionHe: "כרית ביטחון כלכלית של 3-6 חודשי הוצאות חיים, נגישה מיידית למקרי חירום בלתי צפויים.",
    lottieSource: LOTTIE.shield,
    chapterId: 1,
  },
  {
    id: "concept-13",
    titleHe: "תזרים מזומנים",
    descriptionHe: "ההפרש בין הכנסות להוצאות בתקופה מסוימת. תזרים חיובי = נכנס יותר ממה שיוצא.",
    lottieSource: LOTTIE.coins,
    chapterId: 1,
  },
  {
    id: "concept-15",
    titleHe: "עלות אלטרנטיבית",
    descriptionHe: "מה שאתה מפסיד כשאתה בוחר אפשרות אחת על פני אחרת. כל בחירה כלכלית = ויתור על משהו אחר.",
    lottieSource: LOTTIE.balance,
    chapterId: 1,
  },
  {
    id: "concept-19",
    titleHe: "הוצאות קבועות vs משתנות",
    descriptionHe: "קבועות: שכירות, ביטוח, מנויים. משתנות: אוכל, בילויים, קניות. על המשתנות קל יותר לחסוך.",
    lottieSource: LOTTIE.book,
    chapterId: 1,
  },
  {
    id: "concept-27",
    titleHe: "חיסכון אוטומטי",
    descriptionHe: "הוראת קבע לחיסכון ביום שמקבלים משכורת. \"תשלם לעצמך קודם\", לפני שמספיקים לבזבז.",
    lottieSource: LOTTIE.clock,
    chapterId: 1,
  },

  // Chapter 2: ביטחון
  {
    id: "concept-9",
    titleHe: "דירוג אשראי",
    descriptionHe: "ציון שמשקף את האמינות הפיננסית שלך. דירוג גבוה = ריבית נמוכה יותר על הלוואות.",
    lottieSource: LOTTIE.star,
    chapterId: 2,
  },
  {
    id: "concept-12",
    titleHe: "קרן פנסיה",
    descriptionHe: "חיסכון ארוך טווח לפרישה. המעסיק והעובד מפרישים יחד, ומקבלים הטבות מס משמעותיות.",
    lottieSource: LOTTIE.trophy,
    chapterId: 2,
  },
  {
    id: "concept-21",
    titleHe: "ביטוח חיים",
    descriptionHe: "מגן כלכלי על המשפחה במקרה מוות. ביטוח ריסק = זול ומכסה תקופה מוגדרת.",
    lottieSource: LOTTIE.shield,
    chapterId: 2,
  },
  {
    id: "concept-23",
    titleHe: "קרן השתלמות",
    descriptionHe: "חיסכון לטווח של 6 שנים, פטור ממס עד תקרת ההפקדה (~₪20K/שנה). אחד מהמכשירים הכי משתלמים בישראל.",
    lottieSource: LOTTIE.gift,
    chapterId: 2,
  },
  {
    id: "concept-26",
    titleHe: "תעריף מס שולי",
    descriptionHe: "אחוז המס על השקל האחרון שהרווחת. בישראל: מדרגות מ-10% ועד 50% על הכנסה גבוהה.",
    lottieSource: LOTTIE.portfolio,
    chapterId: 2,
  },

  // Chapter 3: יציבות
  {
    id: "concept-2",
    titleHe: "אינפלציה",
    descriptionHe: "עליית מחירים כללית שמקטינה את כוח הקנייה של הכסף. 100 ש\"ח היום שווים פחות מ-100 ש\"ח בעוד 10 שנים.",
    lottieSource: LOTTIE.decrease,
    chapterId: 3,
  },
  {
    id: "concept-6",
    titleHe: "מס רווחי הון",
    descriptionHe: "מס של 25% על רווחים ממכירת ניירות ערך, נדל\"ן להשקעה ונכסים פיננסיים אחרים בישראל.",
    lottieSource: LOTTIE.portfolio,
    chapterId: 3,
  },
  {
    id: "concept-8",
    titleHe: "ריבית בנק ישראל",
    descriptionHe: "הריבית שבנק ישראל קובע ומשפיעה על עלות האשראי, תשואת החיסכון, ושער החליפין.",
    lottieSource: LOTTIE.building,
    chapterId: 3,
  },
  {
    id: "concept-20",
    titleHe: "שער חליפין",
    descriptionHe: "היחס בין ערך של שני מטבעות. כשהדולר עולה, יבוא מתייקר וייצוא משתלם יותר.",
    lottieSource: LOTTIE.coinDollar,
    chapterId: 3,
  },
  {
    id: "concept-22",
    titleHe: "ריבית צמודה למדד",
    descriptionHe: "ריבית שמתעדכנת לפי מדד המחירים לצרכן, שומרת על ערך הכסף גם בתקופות אינפלציה.",
    lottieSource: LOTTIE.lineChart,
    chapterId: 3,
  },
  {
    id: "concept-29",
    titleHe: "עמלות נסתרות",
    descriptionHe: "דמי ניהול, עמלות קנייה/מכירה, דמי משמרת, הכל מכרסם בתשואה. חשוב להשוות לפני שבוחרים.",
    lottieSource: LOTTIE.bulb,
    chapterId: 3,
  },

  // Chapter 4: צמיחה
  {
    id: "concept-5",
    titleHe: "מדד S&P 500",
    descriptionHe: "מדד של 500 החברות הגדולות בארה\"ב. השקעה במדד מאפשרת פיזור רחב בקנייה אחת.",
    lottieSource: LOTTIE.barChartGrowth,
    chapterId: 4,
  },
  {
    id: "concept-7",
    titleHe: "ETF, קרן סל",
    descriptionHe: "קרן שנסחרת בבורסה ועוקבת אחרי מדד. דרך זולה ופשוטה להשקיע בשוק ההון עם פיזור מובנה.",
    lottieSource: LOTTIE.portfolio,
    chapterId: 4,
  },
  {
    id: "concept-10",
    titleHe: "תשואה שנתית",
    descriptionHe: "אחוז הרווח או ההפסד על השקעה במהלך שנה. תשואה ממוצעת של S&P 500: כ-10% בשנה.",
    lottieSource: LOTTIE.growth,
    chapterId: 4,
  },
  {
    id: "concept-11",
    titleHe: "פיזור סיכונים",
    descriptionHe: "אל תשים את כל הביצים בסל אחד, פיזור בין סוגי נכסים שונים מקטין את הסיכון הכולל.",
    lottieSource: LOTTIE.compass,
    chapterId: 4,
  },
  {
    id: "concept-16",
    titleHe: "מניה",
    descriptionHe: "חלק בבעלות על חברה. כשהחברה מצליחה, ערך המניה עולה ואתה מרוויח.",
    lottieSource: LOTTIE.barChart,
    chapterId: 4,
  },
  {
    id: "concept-17",
    titleHe: "אגרת חוב",
    descriptionHe: "הלוואה שאתה נותן לממשלה או לחברה. בתמורה מקבלים ריבית קבועה, פחות סיכון מהשקעה במניות.",
    lottieSource: LOTTIE.lock,
    chapterId: 4,
  },
  {
    id: "concept-18",
    titleHe: "דיבידנד",
    descriptionHe: "חלוקת רווחים של חברה לבעלי המניות שלה. הכנסה פסיבית שמתקבלת בלי למכור את המניה.",
    lottieSource: LOTTIE.coinDollar,
    chapterId: 4,
  },

  // Chapter 5: חופש כלכלי
  {
    id: "concept-14",
    titleHe: "ריבית נומינלית vs ריאלית",
    descriptionHe: "ריבית נומינלית = הריבית המוצהרת. ריבית ריאלית = אחרי הפחתת אינפלציה. זה מה שבאמת משנה.",
    lottieSource: LOTTIE.brain,
    chapterId: 5,
  },
  {
    id: "concept-24",
    titleHe: "מינוף פיננסי",
    descriptionHe: "שימוש בכסף שאול כדי להגדיל השקעה. מגביר רווחים, אבל גם הפסדים. סיכון גבוה.",
    lottieSource: LOTTIE.rocket,
    chapterId: 5,
  },
  {
    id: "concept-25",
    titleHe: "נדל\"ן מניב",
    descriptionHe: "נכס שמייצר הכנסה שוטפת מדמי שכירות. דורש הון התחלתי גבוה אבל נחשב יציב יחסית.",
    lottieSource: LOTTIE.home,
    chapterId: 5,
  },
  {
    id: "concept-28",
    titleHe: "כלל ה-72",
    descriptionHe: "מחלקים 72 בתשואה השנתית = שנים להכפלת הכסף. למשל: ב-8% תשואה, הכסף מוכפל תוך 9 שנים.",
    lottieSource: LOTTIE.target,
    chapterId: 5,
  },
  {
    id: "concept-30",
    titleHe: "FIRE, עצמאות כלכלית",
    descriptionHe: "Financial Independence, Retire Early. חסוך 50%+ מההכנסה, השקע, ופרוש מוקדם מהעבודה.",
    lottieSource: LOTTIE.fire,
    chapterId: 5,
  },

  // ── 2026-05-30 audit expansion: Israeli-specific + general concepts ──
  // Concepts 31-50 — runway extended from 30 to 50 days. Israeli-specific
  // additions matter more than US-imported abstractions for Hebrew Gen-Z.
  {
    id: "concept-31",
    titleHe: "נקודות זיכוי במס",
    descriptionHe: "כל ישראלי מקבל 2.25 נקודות זיכוי בסיסיות. בשנת 2025 — כ-242 ש\"ח/חודש, פחות מס. תוספות לתואר, ילדים, חיילים משוחררים.",
    lottieSource: LOTTIE.gift,
    chapterId: 2,
  },
  {
    id: "concept-32",
    titleHe: "פטור מס שכר דירה",
    descriptionHe: "מי שמשכיר דירה למגורים ב-2025 פטור ממס על שכר דירה עד 5,654 ש\"ח/חודש. מעבר לתקרה — מסלולי מס שונים.",
    lottieSource: LOTTIE.home,
    chapterId: 2,
  },
  {
    id: "concept-33",
    titleHe: "ריבית פריים",
    descriptionHe: "הריבית הבסיסית שהבנקים גובים, מבוססת על ריבית בנק ישראל + 1.5%. רוב המשכנתאות והלוואות צמודות לפריים.",
    lottieSource: LOTTIE.building,
    chapterId: 3,
  },
  {
    id: "concept-34",
    titleHe: "מס רכישה",
    descriptionHe: "מס על קניית דירה. דירה ראשונה: מדורג, פטור עד ~1.97M ש\"ח. דירה שנייה: 8% מהשקל הראשון, ומעלה.",
    lottieSource: LOTTIE.home,
    chapterId: 3,
  },
  {
    id: "concept-35",
    titleHe: "תיק עוקב מדד",
    descriptionHe: "תיק השקעות שמחקה ביצועי מדד (S&P 500, ת\"א 125). דמי ניהול נמוכים, אין צורך לבחור מניות. גישת ההשקעה הפסיבית הקלאסית.",
    lottieSource: LOTTIE.portfolio,
    chapterId: 4,
  },
  {
    id: "concept-36",
    titleHe: "מסלול פנסיוני מנייתי",
    descriptionHe: "מסלול פנסיה עם 75%+ במניות. תשואה היסטורית גבוהה, אבל תנודתי. מתאים לצעירים שעוד 30+ שנה לפרישה.",
    lottieSource: LOTTIE.barChartGrowth,
    chapterId: 4,
  },
  {
    id: "concept-37",
    titleHe: "תיק 60/40",
    descriptionHe: "פיזור קלאסי: 60% מניות, 40% אג\"ח. איזון בין צמיחה וביטחון. בסיס לתיקים גלובליים מזה עשרות שנים.",
    lottieSource: LOTTIE.balance,
    chapterId: 4,
  },
  {
    id: "concept-38",
    titleHe: "ביטוח מנהלים",
    descriptionHe: "ביטוח חיים + פנסיה דרך המעסיק עם הטבות מס. פחות גמיש מקופת גמל. בעיקר בכירים בפנסיה ותיקה.",
    lottieSource: LOTTIE.shield,
    chapterId: 2,
  },
  {
    id: "concept-39",
    titleHe: "ריבית ריאלית",
    descriptionHe: "ריבית נומינלית פחות שיעור האינפלציה. אם הבנק נותן 3% ואינפלציה 2%, הריבית הריאלית = 1%. מה שבאמת מרוויחים.",
    lottieSource: LOTTIE.lineChart,
    chapterId: 3,
  },
  {
    id: "concept-40",
    titleHe: "DCA, פיזור על פני זמן",
    descriptionHe: "Dollar Cost Averaging. השקעת סכום קבוע כל חודש, במקום הכל בבת אחת. ממוצע מחיר לאורך זמן — קונים יותר כשזול.",
    lottieSource: LOTTIE.clock,
    chapterId: 4,
  },
  {
    id: "concept-41",
    titleHe: "מענק עבודה (מס הכנסה שלילי)",
    descriptionHe: "תוספת כספית מהמדינה לעובדים עם שכר נמוך-בינוני, עם ילדים. דורש הגשת תביעה אקטיבית. רוב הזכאים לא תובעים.",
    lottieSource: LOTTIE.coinDollar,
    chapterId: 2,
  },
  {
    id: "concept-42",
    titleHe: "נקודת איזון פיננסית",
    descriptionHe: "המצב בו הכנסות פסיביות (השקעות, שכ\"ד) מכסות את ההוצאות. רגע הקסם של עצמאות פיננסית — אין יותר צורך 'לעבוד'.",
    lottieSource: LOTTIE.target,
    chapterId: 5,
  },
  {
    id: "concept-43",
    titleHe: "אפקט עיגון",
    descriptionHe: "הטיה קוגניטיבית: מחיר ההתחלה (עיגון) משפיע על כל ההחלטות הבאות. הסיבה שמבצעים מציגים 'מחיר רגיל גבוה' לידם.",
    lottieSource: LOTTIE.brain,
    chapterId: 5,
  },
  {
    id: "concept-44",
    titleHe: "אפקט יציבות (Status Quo Bias)",
    descriptionHe: "נטייה להישאר עם המצב הקיים גם כשעדיף לשנות. הסיבה שאנשים נשארים עם אותה קרן פנסיה גרועה במשך עשורים.",
    lottieSource: LOTTIE.brain,
    chapterId: 5,
  },
  {
    id: "concept-45",
    titleHe: "אינפלציית נכסים",
    descriptionHe: "עליית מחירי מניות, נדל\"ן וקריפטו במהירות גבוהה ממוצרי הצריכה. גורמת לפער עשירים-עניים כי נכסים מתייקרים מהר ממשכורת.",
    lottieSource: LOTTIE.decrease,
    chapterId: 3,
  },
  {
    id: "concept-46",
    titleHe: "התחייבות vs נכס",
    descriptionHe: "נכס מכניס כסף לכיס (תיק השקעות, נדל\"ן מושכר). התחייבות מוציאה כסף מהכיס (רכב חדש, חוב צרכני). פשוט אבל קריטי.",
    lottieSource: LOTTIE.balance,
    chapterId: 1,
  },
  {
    id: "concept-47",
    titleHe: "פטור מס לקופת גמל להשקעה",
    descriptionHe: "ניתן להפקיד עד ~80K ש\"ח לשנה. אחרי גיל 60 — הכל פטור ממס רווחי הון. כלי חיסכון חזק וגמיש.",
    lottieSource: LOTTIE.gift,
    chapterId: 2,
  },
  {
    id: "concept-48",
    titleHe: "הון אנושי",
    descriptionHe: "כלל הכישורים, החינוך והניסיון שלכם — הנכס הכלכלי הגדול ביותר עד שצוברים הון פיננסי. השקעה בלמידה משתלמת מהר.",
    lottieSource: LOTTIE.book,
    chapterId: 1,
  },
  {
    id: "concept-49",
    titleHe: "מסי פירות (Sin Taxes)",
    descriptionHe: "מס מוגבר על מוצרים שהמדינה רוצה להפחית את צריכתם: סיגריות, אלכוהול, משקאות ממותקים. דרך תקציבית חזקה.",
    lottieSource: LOTTIE.portfolio,
    chapterId: 3,
  },
  {
    id: "concept-50",
    titleHe: "תיק חירום נזיל",
    descriptionHe: "3-6 חודשי הוצאות בחשבון נזיל (פיקדון יומי / פק\"מ קצר). לא להשקיע במניות — סיכון נזילות כשצריך אותו.",
    lottieSource: LOTTIE.shield,
    chapterId: 2,
  },
];

/** Look up a specific concept by id. Used by Pearl flow to bind a
 *  topic-matched concept to each pearl (e.g., mod-1-1 → concept-1 ריבית דריבית). */
export function getConceptById(id: string): DailyConcept | null {
  return DAILY_CONCEPTS.find((c) => c.id === id) ?? null;
}
