// All Hebrew UI copy for the Clan Hub — single source of truth

export const S = {
  // ===== GENERAL =====
  clan: 'קלאן',
  clans: 'קלאנים',
  myClan: 'הקלאן שלי',
  clanHub: 'מרכז הקלאן',
  createClan: 'צור קלאן',
  joinClan: 'הצטרף לקלאן',
  leaveClan: 'עזוב קלאן',
  disbandClan: 'פרק קלאן',
  renameClan: 'שנה שם',
  inviteCode: 'קוד הזמנה',
  copyCode: 'העתק קוד',
  clanSettings: 'הגדרות קלאן',
  noClansYet: 'אין קלאן עדיין',
  joinOrCreate: 'הצטרף לקלאן קיים או צור חדש',
  enterCode: 'הכנס קוד קלאן',

  // ===== ROLES =====
  roleLeader: 'מנהיג',
  roleDeputy: 'סגן',
  roleMember: 'חבר',

  // ===== TABS =====
  tabOverview: 'סקירה',
  tabChat: 'צ\'אט',
  tabDonations: 'תרומות',
  tabGroupBuy: 'רכישה',
  tabMembers: 'חברים',

  // ===== OVERVIEW TAB =====
  weeklyGoals: 'יעדי השבוע',
  weeklyGoalsSubtitle: 'השיגו יחד לפתוח את האסם',
  topContributors: 'תורמים מובילים',
  membersPreview: 'חברי הקלאן',
  seeAll: 'ראה הכל',

  // ===== CHEST =====
  clanChest: 'אסם הקלאן',
  chestLocked: 'האסם נעול',
  chestReady: 'האסם מוכן!',
  chestProgress: (current: number, total: number) => `${current} / ${total} נקודות`,
  claimChest: 'פתח אסם',
  chestClaimed: 'האסם נפתח! 🎉',
  nextChest: 'האסם הבא',
  claimedThisWeek: 'נפתח השבוע ✓',

  // ===== CHAT TAB =====
  chatPlaceholder: 'כתוב הודעה...',
  chatSend: 'שלח',
  chatEmpty: 'אין הודעות עדיין. שלח הודעה ראשונה!',
  typing: 'מקליד...',

  // ===== DONATIONS TAB =====
  donations: 'תרומות',
  donateNow: 'תרום עכשיו',
  requestDonation: 'בקש תרומה',
  myRequest: 'הבקשה שלך',
  donorsCount: (n: number) => `${n} תורמים`,
  dailyCap: (used: number, max: number) => `${used}/${max} נשארו`,
  dailyCapReached: 'הגעת לתקרה היומית',
  thankDonor: 'תודה! 🙏',
  thanked: 'נשלח תודה ✓',
  donationNote: 'סיבה (אופציונלי)',
  chooseCurrency: 'בחר מטבע',
  chooseAmount: 'בחר סכום',
  coins: 'מטבעות',
  gems: 'ג\'מים',
  reputation: 'מוניטין',
  reputationGain: (n: number) => `+${n} מוניטין`,
  expiresIn: (h: number) => `פג תוקף בעוד ${h} שעות`,
  openRequests: 'בקשות פתוחות',
  noRequests: 'אין בקשות פתוחות',
  fulfillRequest: 'מולא ✓',
  expiredRequest: 'פג תוקף',
  donationCap_coins: `תקרה יומית: ${50} 🪙`,
  donationCap_gems: `תקרה יומית: ${5} 💎`,
  progress: (received: number, requested: number) => `${received} / ${requested}`,
  donateCoins: (n: number) => `תרום ${n} 🪙`,
  donateGems: (n: number) => `תרום ${n} 💎`,

  // ===== GROUP BUY TAB =====
  groupBuy: 'רכישה משותפת',
  groupBuySubtitle: 'קנו נכסים יחד וחלקו הכנסה פסיבית',
  startProject: 'התחל פרויקט חדש',
  contribute: 'הצטרף לרכישה',
  contributed: 'תרמת ✓',
  fundingProgress: (pct: number) => `${pct}% מומן`,
  funded: 'מומן! 🎉',
  activeProjects: 'פרויקטים פעילים',
  fundedAssets: 'נכסים שנרכשו',
  noProjects: 'אין פרויקטים פעילים',
  startFirst: 'התחל פרויקט ראשון',
  dailyYield: 'הכנסה יומית',
  yourShare: 'החלק שלך',
  totalRaised: (n: number) => `${n.toLocaleString('he-IL')} ₪ נאסף`,
  goalAmount: (n: number) => `יעד: ${n.toLocaleString('he-IL')}`,
  passiveIncome: 'הכנסה פסיבית יומית',
  claimPayout: 'קבל הכנסה',
  claimedToday: 'נגבה היום ✓',
  yourContribution: 'תרומתך',
  chooseCurrencyAndAmount: 'בחר מטבע וסכום',
  fantasyCash: 'כסף פנטזי',

  // ===== PROJECT TEMPLATES =====
  chooseTemplate: 'בחר סוג נכס',
  templateMall: 'קניון',
  templateApartment: 'דירה',
  templateRestaurant: 'מסעדה',
  templateGoldcoin: 'מטבע זהב',
  projectFunded: (name: string) => `הקלאן רכש את ${name}! 🏆`,

  // ===== MEMBERS TAB =====
  members: 'חברים',
  membersCount: (n: number) => `${n} חברים`,
  sortByXP: 'לפי XP',
  sortByDonations: 'לפי תרומות',
  sortByShare: 'לפי נכסים',
  kick: 'הוצא מהקלאן',
  promote: 'קדם לסגן',
  demote: 'הורד לחבר',
  challengeToDuel: 'אתגר לדו-קרב ⚔️',
  sendDonation: 'תרום',
  stats_xp: (n: number) => `${n.toLocaleString('he-IL')} XP`,
  stats_coins: (n: number) => `${n.toLocaleString('he-IL')} 🪙`,
  stats_rep: (n: number) => `${n} מוניטין`,
  joinedRecently: 'הצטרף לאחרונה',

  // ===== SYSTEM CHAT EVENTS =====
  sys_member_joined: (name: string) => `${name} הצטרף לקלאן! 🎉`,
  sys_member_left: (name: string) => `${name} עזב את הקלאן`,
  sys_donation_sent: (from: string, amount: number, currency: string) =>
    `${from} תרם ${amount} ${currency === 'coins' ? '🪙' : '💎'}`,
  sys_donation_request: (name: string) => `${name} מבקש תרומה`,
  sys_group_buy_started: (name: string) => `נפתחה קבוצת רכישה: ${name} 🏬`,
  sys_group_buy_funded: (name: string) => `הקלאן רכש את ${name}! 🏆`,
  sys_group_buy_payout: (name: string) => `הכנסה מ-${name} חולקה 💰`,
  sys_chest_unlocked: 'האסם נפתח! 🎁',
  sys_weekly_reset: 'שבוע חדש — יעדים חדשים! 🔄',
  sys_tier_promoted: (tier: string) => `הקלאן עלה לדרגת ${tier}! 🥇`,

  // ===== MONETIZATION CHIPS =====
  chip_chest_multiplier: 'Pro: צ\'סט x2 ✦',
  chip_premium_emblem: 'סמל קלאן פרימיום ✦ 50 💎',
  chip_double_chest: 'אסם כפול עם FinPlay Pro',
  chip_accelerate: 'האץ x2 רכישה ✦ 10 💎',
  chip_donation_cap: 'הגדל תקרה יומית ל-100 ✦ 5 💎',
  chip_pro_stats: 'Pro: סטטיסטיקות מלאות',
  chip_shark_chat: 'Pro: הודעות ללא הגבלה',
  upgrade: 'שדרג',
  dismiss: 'סגור',

  // ===== ONBOARDING =====
  onboarding_title: 'הקלאן שלך מחכה',
  onboarding_subtitle: 'בנה קהילה, רכשו נכסים יחד, ונצחו יחד',
  onboarding_create: 'צור קלאן חדש',
  onboarding_join: 'הצטרף עם קוד',
  onboarding_feature1: 'צ\'אט קבוצתי עם חברים',
  onboarding_feature2: 'רכישה משותפת של נכסים',
  onboarding_feature3: 'אסם שבועי עם פרסים',

  // ===== FRIENDS HUB =====
  friendsHub: 'חברים',
  activityFeed: 'פעילות אחרונה',
  league: 'ליגה',
  leaderboard: 'לוח תוצאות',
  duels: 'דו-קרב',
  clash: 'קלאש',
  referral: 'הזמן חברים',
  sharkChat: 'דבר עם שארק',
  fantasyLeague: 'פנטזיליג מניות',
  viewAll: 'ראה הכל',
  yourRank: 'הדירוג שלך',
  weeklyRank: 'דירוג שבועי',

  // ===== ERRORS & EMPTY =====
  errorGeneric: 'משהו השתבש. נסה שוב.',
  loadingData: 'טוען...',
  noData: 'אין מידע',
} as const;
