import type { ShopCategory, ShopItem } from './types';

export const SHOP_ITEMS: readonly ShopItem[] = [
  // ── לבבות (urgent — expensive in coins, cheap in gems → gem incentive) ──
  {
    id: 'heart-refill-1',
    category: 'hearts',
    name: 'מילוי לב אחד',
    description: 'מוסיף לב אחד באופן מיידי. בשביל מי שלא רוצה לחכות 4 שעות.',
    coinCost: 1500,
    emoji: '❤️',
    lottieSource: require('../../../assets/lottie/wired-flat-20-love-heart-hover-heartbeat.json'),
  },
  {
    id: 'heart-refill-full',
    category: 'hearts',
    name: 'מילוי כל הלבבות',
    description: 'מחזיר את כל 5 הלבבות לתפוסה מלאה. חזרה לפעולה!',
    coinCost: 5000,
    emoji: '💖',
    lottieSource: require('../../../assets/lottie/wired-flat-20-love-heart-hover-heartbeat.json'),
  },

  // ── רמזים ──
  {
    id: 'hint-single',
    category: 'hints',
    name: 'רמז לשאלה',
    description: 'חושף תשובה אחת שגויה בקוויז בלי להפסיד XP.',
    coinCost: 1200,
    emoji: '💡',
    lottieSource: require('../../../assets/lottie/wired-flat-36-bulb-hover-blink.json'),
  },
  {
    id: 'hint-bundle',
    category: 'hints',
    name: 'חבילת רמזים (×5)',
    description: 'חמישה טוקני רמז במחיר מוזל. לעולם לא תיתקע.',
    coinCost: 5000,
    emoji: '🎯',
    lottieSource: require('../../../assets/lottie/wired-flat-458-goal-target-hover-hit.json'),
  },

  // ── הגנה ──
  {
    id: 'streak-freeze',
    category: 'protection',
    name: 'הקפאת סטריק',
    description: 'מגן על הסטריק שלך ליום אחד שפספסת. הופעל אוטומטית.',
    coinCost: 3000,
    emoji: '🧊',
    lottieSource: require('../../../assets/lottie/wired-flat-457-shield-security-hover-pinch.json'),
  },
  {
    id: 'streak-freeze-bundle',
    category: 'protection',
    name: 'הקפאת סטריק (×3)',
    description: 'שלוש הקפאות סטריק. שמור על המומנטום שלך.',
    coinCost: 7500,
    emoji: '🛡️',
    lottieSource: require('../../../assets/lottie/wired-flat-457-shield-security-hover-pinch.json'),
  },

  // ── קוסמטיקה (aspirational — weeks of saving) ──
  {
    id: 'badge-neon',
    category: 'cosmetics',
    name: 'תג ניאון',
    description: 'תג זוהר שמופיע ליד השם שלך בלוח התוצאות.',
    coinCost: 5000,
    emoji: '✨',
    lottieSource: require('../../../assets/lottie/wired-flat-2474-sparkles-glitter-hover-pinch.json'),
  },
  {
    id: 'theme-cyber',
    category: 'cosmetics',
    name: 'ערכת נושא סייבר',
    description: 'שנה את עיצוב הפירמידה לסגנון סייברפנק.',
    coinCost: 15000,
    emoji: '🌐',
    lottieSource: require('../../../assets/lottie/wired-flat-1307-hub-network-hover-pinch.json'),
  },

  // ── פרימיום (ג'מים) ──
  {
    id: 'chest-skip-timer',
    category: 'premium',
    name: 'דילוג על טיימר תיבה',
    description: 'פתח תיבה שנעולה מיד בלי לחכות. חסוך שעות!',
    coinCost: 0,
    gemCost: 5,
    emoji: '⏩',
    lottieSource: require('../../../assets/lottie/3D Treasure Box.json'),
  },

  // ── אווטארים פרימיום ──
  {
    id: 'avatar-koala',
    category: 'avatars',
    name: 'הישנוני',
    description: 'קואלה רגועה — כי השקעות לטווח ארוך דורשות סבלנות.',
    coinCost: 0,
    gemCost: 50,
    emoji: '🐨',
    lottieSource: require('../../../assets/lottie/wired-flat-44-avatar-user-in-circle-hover-looking-around.json'),
  },
  {
    id: 'avatar-king',
    category: 'avatars',
    name: 'המלוכה',
    description: 'אווטר מלכותי אקסקלוסיבי. רק לאלו שמגיעים לראש.',
    coinCost: 0,
    gemCost: 100,
    emoji: '👑',
    lottieSource: require('../../../assets/lottie/Crown.json'),
  },
  {
    id: 'avatar-robot',
    category: 'avatars',
    name: 'FinBot AI',
    description: 'הרובוט שמנתח שוקי הון 24/7. AI-powered avatar.',
    coinCost: 0,
    gemCost: 150,
    emoji: '🤖',
    lottieSource: require('../../../assets/lottie/robot.json'),
  },
  {
    id: 'avatar-unicorn',
    category: 'avatars',
    name: 'הנדיר',
    description: 'חד-קרן — כי להיות נדיר זו אסטרטגיה פיננסית.',
    coinCost: 0,
    gemCost: 250,
    emoji: '🦄',
    lottieSource: require('../../../assets/lottie/wired-flat-2474-sparkles-glitter-hover-pinch.json'),
  },
  {
    id: 'avatar-dragon',
    category: 'avatars',
    name: 'הדרקון',
    description: 'דרקון עוצמתי ששומר על האוצר שלך.',
    coinCost: 0,
    gemCost: 400,
    emoji: '🐲',
    lottieSource: require('../../../assets/lottie/wired-flat-3139-rocket-space-alt-hover-pinch.json'),
  },
  {
    id: 'avatar-phoenix',
    category: 'avatars',
    name: 'הפניקס',
    description: 'הפניקס שקם מהאפר — מושלם למי שהתחיל מחדש.',
    coinCost: 0,
    gemCost: 600,
    emoji: '🔥',
    lottieSource: require('../../../assets/lottie/wired-flat-1103-confetti-hover-pinch.json'),
  },
  {
    id: 'avatar-diamond',
    category: 'avatars',
    name: 'הפרימיום',
    description: 'יהלום — עבור מי שמוכן לשלם פרימיום על הכל.',
    coinCost: 0,
    gemCost: 800,
    emoji: '💎',
    lottieSource: require('../../../assets/lottie/Diamond.json'),
  },
  {
    id: 'avatar-rocket',
    category: 'avatars',
    name: 'האסטרונאוט',
    description: 'לטוס לירח! מתאים למשקיעים אופטימיים במיוחד.',
    coinCost: 0,
    gemCost: 1200,
    emoji: '🚀',
    lottieSource: require('../../../assets/lottie/wired-flat-489-rocket-space-hover-flying.json'),
  },
];

export const SHOP_CATEGORIES: readonly { key: ShopCategory; label: string; lottieSource?: number }[] = [
  { key: 'hearts', label: 'לבבות', lottieSource: require('../../../assets/lottie/wired-flat-20-love-heart-hover-heartbeat.json') },
  { key: 'hints', label: 'רמזים', lottieSource: require('../../../assets/lottie/wired-flat-36-bulb-hover-blink.json') },
  { key: 'protection', label: 'הגנה', lottieSource: require('../../../assets/lottie/wired-flat-457-shield-security-hover-pinch.json') },
  { key: 'cosmetics', label: 'קוסמטיקה', lottieSource: require('../../../assets/lottie/wired-flat-2474-sparkles-glitter-hover-pinch.json') },
  { key: 'premium', label: 'פרימיום', lottieSource: require('../../../assets/lottie/Diamond.json') },
  { key: 'avatars', label: 'אווטארים', lottieSource: require('../../../assets/lottie/wired-flat-44-avatar-user-in-circle-hover-looking-around.json') },
];
