import type { ShopCategory, ShopItem } from './types';

export const SHOP_ITEMS: readonly ShopItem[] = [
  // ── לבבות (urgent, expensive in coins, cheap in gems → gem incentive) ──
  {
    id: 'heart-refill-1',
    category: 'hearts',
    name: 'מילוי לב אחד',
    description: 'מוסיף לב אחד באופן מיידי. בשביל מי שלא רוצה לחכות 4 שעות.',
    coinCost: 1500,
    emoji: '❤️',
    lottieSource: require('../../../assets/lottie/wired-flat-20-love-heart-hover-heartbeat.json'),
  },
  {
    id: 'heart-refill-full',
    category: 'hearts',
    name: 'מילוי כל הלבבות',
    description: 'מחזיר את כל 5 הלבבות לתפוסה מלאה. חזרה לפעולה!',
    coinCost: 5000,
    emoji: '💖',
    lottieSource: require('../../../assets/lottie/wired-flat-20-love-heart-hover-heartbeat.json'),
  },

  // ── הגנה ──
  {
    id: 'streak-freeze',
    category: 'protection',
    name: 'הקפאת סטריק',
    description: 'מגן על הסטריק שלך ליום אחד שפספסת. הופעל אוטומטית.',
    coinCost: 3000,
    emoji: '🧊',
    lottieSource: require('../../../assets/lottie/wired-flat-457-shield-security-hover-pinch.json'),
  },
  {
    id: 'streak-freeze-bundle',
    category: 'protection',
    name: 'הקפאת סטריק (×3)',
    description: 'שלוש הקפאות סטריק. שמור על המומנטום שלך.',
    coinCost: 7500,
    emoji: '🛡️',
    lottieSource: require('../../../assets/lottie/wired-flat-457-shield-security-hover-pinch.json'),
  },
  // ── הגנה Premium (Streak Insurance — whale-tier protection) ──
  {
    id: 'streak-shield-week',
    category: 'protection',
    name: 'מגן שבוע',
    description: 'מבטח עד 3 ימים שפספסתם השבוע. בלי שחיקת רצף.',
    coinCost: 0,
    gemCost: 200,
    emoji: '🛡️',
    lottieSource: require('../../../assets/lottie/wired-flat-457-shield-security-hover-pinch.json'),
  },
  {
    id: 'streak-shield-month',
    category: 'protection',
    name: 'מגן חודש',
    description: 'מבטח עד 7 ימים שפספסתם החודש. ביטוח Pro לסטרייקרים.',
    coinCost: 0,
    gemCost: 600,
    emoji: '⚔️',
    lottieSource: require('../../../assets/lottie/wired-flat-457-shield-security-hover-pinch.json'),
  },
  {
    id: 'streak-revival-elite',
    category: 'protection',
    name: 'תחיית רצף Elite',
    description: 'מחזיר רצף שנשבר עד 60 ימים אחורה. חד-פעמי.',
    coinCost: 0,
    gemCost: 1500,
    emoji: '💎',
    lottieSource: require('../../../assets/lottie/Diamond.json'),
  },

  // ── Boosters (Coin Master "Power Hour" / Brawl Stars "Star Boost" pattern) ──
  {
    id: 'boost-xp-2x-1h',
    category: 'boosts',
    name: 'XP כפול לשעה',
    description: 'כל XP מהשיעור הבא ולשעה אחת — כפול. צאו ללמוד.',
    coinCost: 0,
    gemCost: 80,
    emoji: '⚡',
    lottieSource: require('../../../assets/lottie/wired-flat-489-rocket-space-hover-flying.json'),
  },
  {
    id: 'boost-coins-2x-1h',
    category: 'boosts',
    name: 'מטבעות כפול לשעה',
    description: 'כל מטבע מלמידה לשעה — כפול. אגרסיבי על אגרסיביות.',
    coinCost: 0,
    gemCost: 80,
    emoji: '🪙',
    lottieSource: require('../../../assets/lottie/wired-flat-2474-sparkles-glitter-hover-pinch.json'),
  },
  {
    id: 'boost-mega-1h',
    category: 'boosts',
    name: 'Mega Boost לשעה',
    description: 'XP כפול + מטבעות כפול + תגמולי משימות כפולים. לשעה.',
    coinCost: 0,
    gemCost: 150,
    emoji: '🚀',
    lottieSource: require('../../../assets/lottie/wired-flat-489-rocket-space-hover-flying.json'),
  },
  {
    id: 'boost-weekend',
    category: 'boosts',
    name: 'Weekend Boost',
    description: '1.5× לכל הלמידה משישי 18:00 עד שבת 22:00. ה-weekend הכי משתלם.',
    coinCost: 0,
    gemCost: 250,
    emoji: '🌅',
    lottieSource: require('../../../assets/lottie/wired-flat-1307-hub-network-hover-pinch.json'),
  },

  // ── אווטארים פרימיום (Pip mascot — 10 archetypes) ──
  // Pricing curve (מוני): geometric ramp 50→1500. Floor 50 = accessible
  // entry; ceiling 1500 = whale bait (Strategist with chess king + crown vibe).
  // Mid-range items (180–500) cluster where most paying users land.
  {
    id: 'avatar-saver',
    category: 'avatars',
    name: 'החוסך',
    description: 'כל מטבע נספר. החיסכון מתחיל היום.',
    coinCost: 0,
    gemCost: 50,
    emoji: '🪙',
    ability: '+5% 🪙 בקוויזים',
  },
  {
    id: 'avatar-learner',
    category: 'avatars',
    name: 'הלומד',
    description: 'ספר ביד, כובע גרדואציה. ידע פיננסי = כוח.',
    coinCost: 0,
    gemCost: 80,
    emoji: '📚',
    ability: '+8% XP בשיעורים',
  },
  {
    id: 'avatar-grower',
    category: 'avatars',
    name: 'המגדל',
    description: 'משקיעים בעצים שצומחים. סבלנות מנצחת.',
    coinCost: 0,
    gemCost: 120,
    emoji: '🌱',
    ability: '+10% XP במשימות',
  },
  {
    id: 'avatar-strong-saver',
    category: 'avatars',
    name: 'החוסך החזק',
    description: 'פיגי בנק וקסדה. מחויב לטווח הארוך.',
    coinCost: 0,
    gemCost: 180,
    emoji: '🐷',
    ability: '+10% 🪙 בקוויזים',
  },
  {
    id: 'avatar-analyst',
    category: 'avatars',
    name: 'המנתח',
    description: 'טאבלט, גרפים, משקפיים. מבוסס נתונים בלבד.',
    coinCost: 0,
    gemCost: 220,
    emoji: '📊',
    ability: '+12% XP מפרקים',
  },
  {
    id: 'avatar-investor',
    category: 'avatars',
    name: 'המשקיע',
    description: 'בונה הון לאט ובטוח. הזמן הוא המנוף האמיתי.',
    coinCost: 0,
    gemCost: 350,
    emoji: '🚀',
    ability: '+15% 🪙 בקוויזים',
  },
  {
    id: 'avatar-trader',
    category: 'avatars',
    name: 'הסוחר',
    description: 'עוקב אחרי השווקים. סבלנות וכלים מנצחים אינסטינקט.',
    coinCost: 0,
    gemCost: 500,
    emoji: '📈',
    ability: '+15% 🪙 ו-+5% XP',
  },
  {
    id: 'avatar-defender',
    category: 'avatars',
    name: 'המגן',
    description: 'מגן וכתר. מי ששומר על ההון שלו — מנצח.',
    coinCost: 0,
    gemCost: 700,
    emoji: '🛡️',
    ability: 'הקפאת רצף + 10% 🪙',
  },
  {
    id: 'avatar-explorer',
    category: 'avatars',
    name: 'החוקר',
    description: 'גלובוס ביד. השקעות בכל העולם.',
    coinCost: 0,
    gemCost: 1000,
    emoji: '🌍',
    ability: '+20% 🪙 מכל מקור',
  },
  {
    id: 'avatar-strategist',
    category: 'avatars',
    name: 'האסטרטג',
    description: 'מלך השחמט וכובע ברט. תכנון מספר צעדים קדימה.',
    coinCost: 0,
    gemCost: 1500,
    emoji: '♟️',
    ability: '+25% XP ו-+25% 🪙',
  },
];

// Categories — only those with shippable items. `hints` and `cosmetics` are
// hidden until their inventory systems exist (purchasing today wouldn't grant
// anything in code). `premium` stays as the future-content placeholder.
export const SHOP_CATEGORIES: readonly { key: ShopCategory; label: string; lottieSource?: number }[] = [
  { key: 'hearts', label: 'לבבות', lottieSource: require('../../../assets/lottie/wired-flat-20-love-heart-hover-heartbeat.json') },
  { key: 'boosts', label: 'בוסטרים', lottieSource: require('../../../assets/lottie/wired-flat-489-rocket-space-hover-flying.json') },
  { key: 'protection', label: 'הגנה', lottieSource: require('../../../assets/lottie/wired-flat-457-shield-security-hover-pinch.json') },
  { key: 'premium', label: 'פרימיום', lottieSource: require('../../../assets/lottie/Diamond.json') },
  { key: 'avatars', label: 'אווטארים', lottieSource: require('../../../assets/lottie/wired-flat-44-avatar-user-in-circle-hover-looking-around.json') },
];
