import type { ShopCategory, ShopItem } from './types';

export const SHOP_ITEMS: readonly ShopItem[] = [
  // ── לבבות (urgent, expensive in coins, cheap in gems → gem incentive) ──
  {
    id: 'heart-refill-1',
    category: 'hearts',
    name: 'מילוי לב אחד',
    description: 'מוסיף לב אחד באופן מיידי. בשביל מי שלא רוצה לחכות 4 שעות.',
    coinCost: 1500,
    emoji: '❤️',
    lottieSource: require('../../../assets/lottie/wired-flat-20-love-heart-hover-heartbeat.json'),
  },
  {
    id: 'heart-refill-full',
    category: 'hearts',
    name: 'מילוי כל הלבבות',
    description: 'מחזיר את כל 5 הלבבות לתפוסה מלאה. חזרה לפעולה!',
    coinCost: 5000,
    emoji: '💖',
    lottieSource: require('../../../assets/lottie/wired-flat-20-love-heart-hover-heartbeat.json'),
  },

  // ── רמזים ──
  {
    id: 'hint-single',
    category: 'hints',
    name: 'רמז לשאלה',
    description: 'חושף תשובה אחת שגויה בקוויז בלי להפסיד XP.',
    coinCost: 1200,
    emoji: '💡',
    lottieSource: require('../../../assets/lottie/wired-flat-36-bulb-hover-blink.json'),
  },
  {
    id: 'hint-bundle',
    category: 'hints',
    name: 'חבילת רמזים (×5)',
    description: 'חמישה טוקני רמז במחיר מוזל. לעולם לא תיתקע.',
    coinCost: 5000,
    emoji: '🎯',
    lottieSource: require('../../../assets/lottie/wired-flat-458-goal-target-hover-hit.json'),
  },

  // ── הגנה ──
  {
    id: 'streak-freeze',
    category: 'protection',
    name: 'הקפאת סטריק',
    description: 'מגן על הסטריק שלך ליום אחד שפספסת. הופעל אוטומטית.',
    coinCost: 3000,
    emoji: '🧊',
    lottieSource: require('../../../assets/lottie/wired-flat-457-shield-security-hover-pinch.json'),
  },
  {
    id: 'streak-freeze-bundle',
    category: 'protection',
    name: 'הקפאת סטריק (×3)',
    description: 'שלוש הקפאות סטריק. שמור על המומנטום שלך.',
    coinCost: 7500,
    emoji: '🛡️',
    lottieSource: require('../../../assets/lottie/wired-flat-457-shield-security-hover-pinch.json'),
  },
  // ── הגנה Premium (Streak Insurance — whale-tier protection) ──
  {
    id: 'streak-shield-week',
    category: 'protection',
    name: 'מגן שבוע',
    description: 'מבטח עד 3 ימים שפספסתם השבוע. בלי שחיקת רצף.',
    coinCost: 0,
    gemCost: 200,
    emoji: '🛡️',
    lottieSource: require('../../../assets/lottie/wired-flat-457-shield-security-hover-pinch.json'),
  },
  {
    id: 'streak-shield-month',
    category: 'protection',
    name: 'מגן חודש',
    description: 'מבטח עד 7 ימים שפספסתם החודש. ביטוח Pro לסטרייקרים.',
    coinCost: 0,
    gemCost: 600,
    emoji: '⚔️',
    lottieSource: require('../../../assets/lottie/wired-flat-457-shield-security-hover-pinch.json'),
  },
  {
    id: 'streak-revival-elite',
    category: 'protection',
    name: 'תחיית רצף Elite',
    description: 'מחזיר רצף שנשבר עד 60 ימים אחורה. חד-פעמי.',
    coinCost: 0,
    gemCost: 1500,
    emoji: '💎',
    lottieSource: require('../../../assets/lottie/Diamond.json'),
  },

  // ── Boosters (Coin Master "Power Hour" / Brawl Stars "Star Boost" pattern) ──
  {
    id: 'boost-xp-2x-1h',
    category: 'boosts',
    name: 'XP כפול לשעה',
    description: 'כל XP מהשיעור הבא ולשעה אחת — כפול. צאו ללמוד.',
    coinCost: 0,
    gemCost: 80,
    emoji: '⚡',
    lottieSource: require('../../../assets/lottie/wired-flat-489-rocket-space-hover-flying.json'),
  },
  {
    id: 'boost-coins-2x-1h',
    category: 'boosts',
    name: 'מטבעות כפול לשעה',
    description: 'כל מטבע מלמידה לשעה — כפול. אגרסיבי על אגרסיביות.',
    coinCost: 0,
    gemCost: 80,
    emoji: '🪙',
    lottieSource: require('../../../assets/lottie/wired-flat-2474-sparkles-glitter-hover-pinch.json'),
  },
  {
    id: 'boost-mega-1h',
    category: 'boosts',
    name: 'Mega Boost לשעה',
    description: 'XP כפול + מטבעות כפול + תגמולי משימות כפולים. לשעה.',
    coinCost: 0,
    gemCost: 150,
    emoji: '🚀',
    lottieSource: require('../../../assets/lottie/wired-flat-489-rocket-space-hover-flying.json'),
  },
  {
    id: 'boost-weekend',
    category: 'boosts',
    name: 'Weekend Boost',
    description: '1.5× לכל הלמידה משישי 18:00 עד שבת 22:00. ה-weekend הכי משתלם.',
    coinCost: 0,
    gemCost: 250,
    emoji: '🌅',
    lottieSource: require('../../../assets/lottie/wired-flat-1307-hub-network-hover-pinch.json'),
  },

  // ── קוסמטיקה (aspirational, weeks of saving) ──
  {
    id: 'badge-neon',
    category: 'cosmetics',
    name: 'תג ניאון',
    description: 'תג זוהר שמופיע ליד השם שלך בלוח התוצאות.',
    coinCost: 5000,
    emoji: '✨',
    lottieSource: require('../../../assets/lottie/wired-flat-2474-sparkles-glitter-hover-pinch.json'),
  },
  {
    id: 'theme-cyber',
    category: 'cosmetics',
    name: 'ערכת נושא סייבר',
    description: 'שנה את עיצוב שביל הלמידה לסגנון סייברפנק.',
    coinCost: 15000,
    emoji: '🌐',
    lottieSource: require('../../../assets/lottie/wired-flat-1307-hub-network-hover-pinch.json'),
  },

  // ── אווטארים פרימיום (קפטן שארק) ──
  {
    id: 'avatar-scholar',
    category: 'avatars',
    name: 'הלומד',
    description: 'קפטן שארק שלומד את היסודות. ידע = כוח.',
    coinCost: 0,
    gemCost: 50,
    emoji: '🦈',
    imageUrl: 'https://8mnwcjygpqev3keg.public.blob.vercel-storage.com/images/avatars/scholar.png?v=4',
  },
  {
    id: 'avatar-saver',
    category: 'avatars',
    name: 'החוסך',
    description: 'כל מטבע נספר. החיסכון מתחיל היום.',
    coinCost: 0,
    gemCost: 100,
    emoji: '🦈',
    imageUrl: 'https://8mnwcjygpqev3keg.public.blob.vercel-storage.com/images/avatars/saver.png?v=4',
  },
  {
    id: 'avatar-analyst',
    category: 'avatars',
    name: 'המנתח',
    description: 'טאבלט ביד, גרפים מולו. מבוסס נתונים.',
    coinCost: 0,
    gemCost: 150,
    emoji: '🦈',
    imageUrl: 'https://8mnwcjygpqev3keg.public.blob.vercel-storage.com/images/avatars/analyst.png?v=4',
  },
  {
    id: 'avatar-piggy',
    category: 'avatars',
    name: 'החוסך החזק',
    description: 'פיגי בנק = ההישג האמיתי. מחויבים לטווח הארוך.',
    coinCost: 0,
    gemCost: 250,
    emoji: '🦈',
    imageUrl: 'https://8mnwcjygpqev3keg.public.blob.vercel-storage.com/images/avatars/piggy.png?v=4',
  },
  {
    id: 'avatar-investor',
    category: 'avatars',
    name: 'המשקיע',
    description: 'מתיק מגוון לפורטפוליו עוצמתי.',
    coinCost: 0,
    gemCost: 400,
    emoji: '🦈',
    imageUrl: 'https://8mnwcjygpqev3keg.public.blob.vercel-storage.com/images/avatars/investor.png?v=4',
  },
  {
    id: 'avatar-earner',
    category: 'avatars',
    name: 'המרוויח',
    description: 'הכסף עובד עבורו. תשואות חכמות לטווח הארוך.',
    coinCost: 0,
    gemCost: 600,
    emoji: '🦈',
    imageUrl: 'https://8mnwcjygpqev3keg.public.blob.vercel-storage.com/images/avatars/earner.png?v=4',
  },
  {
    id: 'avatar-trader',
    category: 'avatars',
    name: 'הסוחר',
    description: 'פעיל בשווקים. ניתוח מבוסס נתונים ותזמון מחושב.',
    coinCost: 0,
    gemCost: 800,
    emoji: '🦈',
    imageUrl: 'https://8mnwcjygpqev3keg.public.blob.vercel-storage.com/images/avatars/trader.png?v=4',
  },
  {
    id: 'avatar-banker',
    category: 'avatars',
    name: 'הבנקאי',
    description: 'פרימיום מקצועי. אליטה פיננסית.',
    coinCost: 0,
    gemCost: 1200,
    emoji: '🦈',
    imageUrl: 'https://8mnwcjygpqev3keg.public.blob.vercel-storage.com/images/avatars/banker.png?v=4',
  },
];

export const SHOP_CATEGORIES: readonly { key: ShopCategory; label: string; lottieSource?: number }[] = [
  { key: 'hearts', label: 'לבבות', lottieSource: require('../../../assets/lottie/wired-flat-20-love-heart-hover-heartbeat.json') },
  { key: 'boosts', label: 'בוסטרים', lottieSource: require('../../../assets/lottie/wired-flat-489-rocket-space-hover-flying.json') },
  { key: 'hints', label: 'רמזים', lottieSource: require('../../../assets/lottie/wired-flat-36-bulb-hover-blink.json') },
  { key: 'protection', label: 'הגנה', lottieSource: require('../../../assets/lottie/wired-flat-457-shield-security-hover-pinch.json') },
  { key: 'cosmetics', label: 'קוסמטיקה', lottieSource: require('../../../assets/lottie/wired-flat-2474-sparkles-glitter-hover-pinch.json') },
  { key: 'premium', label: 'פרימיום', lottieSource: require('../../../assets/lottie/Diamond.json') },
  { key: 'avatars', label: 'אווטארים', lottieSource: require('../../../assets/lottie/wired-flat-44-avatar-user-in-circle-hover-looking-around.json') },
];
