/**
 * SIM: בנה תיק לפי גראהם (Graham Portfolio Builder)
 * 10 fictional stocks, mix of Graham-approved value picks and speculative traps.
 */

import type { GrahamStock } from './grahamPortfolioTypes';

export const BUDGET = 100_000;

/** Color per stock for the allocation bar. */
export const STOCK_COLORS: Record<string, string> = {
  'stable-bank':     '#2563eb',
  'pharma-giant':    '#7c3aed',
  'food-corp':       '#ea580c',
  'green-energy':    '#059669',
  'public-utility':  '#0891b2',
  'young-tech':      '#e11d48',
  'crypto-tech':     '#f59e0b',
  'ev-motors':       '#dc2626',
  'sp500-index':     '#6366f1',
  'income-realty':   '#84cc16',
};

export const GRAHAM_STOCKS: GrahamStock[] = [
  {
    id: 'stable-bank',
    name: 'בנק יציב',
    emoji: '🏦',
    sector: 'בנקאות',
    pe: 10,
    pb: 0.9,
    dividendYears: 20,
    debtToEquity: 0.6,
    earningsGrowth5y: 18,
    currentRatio: 2.5,
    yearsOfProfits: 25,
    marketCapBillion: 45,
  },
  {
    id: 'pharma-giant',
    name: 'ענקית תרופות',
    emoji: '💊',
    sector: 'תרופות',
    pe: 14,
    pb: 1.3,
    dividendYears: 15,
    debtToEquity: 0.4,
    earningsGrowth5y: 22,
    currentRatio: 2.2,
    yearsOfProfits: 30,
    marketCapBillion: 120,
  },
  {
    id: 'food-corp',
    name: 'חברת מזון',
    emoji: '🍞',
    sector: 'צריכה בסיסית',
    pe: 16,
    pb: 1.4,
    dividendYears: 30,
    debtToEquity: 0.3,
    earningsGrowth5y: 12,
    currentRatio: 2.8,
    yearsOfProfits: 40,
    marketCapBillion: 80,
  },
  {
    id: 'green-energy',
    name: 'אנרגיה ירוקה',
    emoji: '🌱',
    sector: 'אנרגיה',
    pe: 8,
    pb: 0.7,
    dividendYears: 5,
    debtToEquity: 0.5,
    earningsGrowth5y: 35,
    currentRatio: 2.1,
    yearsOfProfits: 12,
    marketCapBillion: 15,
  },
  {
    id: 'public-utility',
    name: 'שירותים ציבוריים',
    emoji: '💡',
    sector: 'תשתיות',
    pe: 11,
    pb: 1.1,
    dividendYears: 25,
    debtToEquity: 0.7,
    earningsGrowth5y: 10,
    currentRatio: 2.3,
    yearsOfProfits: 35,
    marketCapBillion: 30,
  },
  {
    id: 'young-tech',
    name: 'טק צעירה',
    emoji: '🚀',
    sector: 'טכנולוגיה',
    pe: 120,
    pb: 15,
    dividendYears: 0,
    debtToEquity: 1.8,
    earningsGrowth5y: 200,
    currentRatio: 0.9,
    yearsOfProfits: 2,
    marketCapBillion: 3,
  },
  {
    id: 'crypto-tech',
    name: 'קריפטו טק',
    emoji: ' מטבעות',
    sector: 'קריפטו',
    pe: 0,
    pb: 25,
    dividendYears: 0,
    debtToEquity: 3.0,
    earningsGrowth5y: -40,
    currentRatio: 0.6,
    yearsOfProfits: 1,
    marketCapBillion: 0.8,
  },
  {
    id: 'ev-motors',
    name: 'רכב חשמלי',
    emoji: '⚡',
    sector: 'רכב',
    pe: 200,
    pb: 18,
    dividendYears: 0,
    debtToEquity: 2.5,
    earningsGrowth5y: -15,
    currentRatio: 0.7,
    yearsOfProfits: 0,
    marketCapBillion: 25,
  },
  {
    id: 'sp500-index',
    name: 'קרן מדד ‎S&P‎ 500',
    emoji: '📊',
    sector: 'מדדים',
    pe: 20,
    pb: 3.5,
    dividendYears: 10,
    debtToEquity: 0.0,
    earningsGrowth5y: 40,
    currentRatio: 5.0,
    yearsOfProfits: 50,
    marketCapBillion: 500,
  },
  {
    id: 'income-realty',
    name: 'נדל"ן מניב',
    emoji: '🏢',
    sector: 'נדל"ן',
    pe: 12,
    pb: 0.8,
    dividendYears: 8,
    debtToEquity: 2.2,
    earningsGrowth5y: 15,
    currentRatio: 1.4,
    yearsOfProfits: 15,
    marketCapBillion: 10,
  },
];
