/**
 * SIM: מחשבון מרווח ביטחון (Margin of Safety Calculator)
 * Pre-loaded example companies with real Q1-2026 data.
 * Stocks match TRADABLE_ASSETS from the trading hub.
 */

import type { StockInput } from './marginSafetyTypes';

export const AAA_YIELD = 4.6;

export const EXAMPLE_STOCKS: StockInput[] = [
  {
    id: 'AAPL',
    name: 'Apple',
    emoji: '🍎',
    price: 246,
    eps: 6.75,
    bookValue: 4.38,
    dividendYield: 0.44,
    debtToEquity: 1.87,
    yearsProfitable: 20,
    growthRate: 8,
    aaaYield: AAA_YIELD,
  },
  {
    id: 'MSFT',
    name: 'Microsoft',
    emoji: '🪟',
    price: 357,
    eps: 12.41,
    bookValue: 36.12,
    dividendYield: 0.70,
    debtToEquity: 0.42,
    yearsProfitable: 30,
    growthRate: 14,
    aaaYield: AAA_YIELD,
  },
  {
    id: 'NVDA',
    name: 'NVIDIA',
    emoji: '🟢',
    price: 165,
    eps: 2.94,
    bookValue: 2.37,
    dividendYield: 0.02,
    debtToEquity: 0.41,
    yearsProfitable: 15,
    growthRate: 55,
    aaaYield: AAA_YIELD,
  },
  {
    id: 'GOOGL',
    name: 'Alphabet',
    emoji: '🔍',
    price: 273,
    eps: 8.04,
    bookValue: 25.09,
    dividendYield: 0.45,
    debtToEquity: 0.10,
    yearsProfitable: 18,
    growthRate: 15,
    aaaYield: AAA_YIELD,
  },
  {
    id: 'META',
    name: 'Meta',
    emoji: '👤',
    price: 579,
    eps: 23.86,
    bookValue: 66.18,
    dividendYield: 0.33,
    debtToEquity: 0.30,
    yearsProfitable: 13,
    growthRate: 18,
    aaaYield: AAA_YIELD,
  },
  {
    id: 'TSLA',
    name: 'Tesla',
    emoji: '⚡',
    price: 353,
    eps: 2.42,
    bookValue: 19.19,
    dividendYield: 0,
    debtToEquity: 0.17,
    yearsProfitable: 5,
    growthRate: 25,
    aaaYield: AAA_YIELD,
  },
  {
    id: 'KO',
    name: 'Coca-Cola',
    emoji: '🥤',
    price: 77,
    eps: 2.69,
    bookValue: 6.41,
    dividendYield: 3.0,
    debtToEquity: 1.72,
    yearsProfitable: 50,
    growthRate: 4,
    aaaYield: AAA_YIELD,
  },
  {
    id: 'TEVA',
    name: 'Teva',
    emoji: '💊',
    price: 29,
    eps: 2.72,
    bookValue: 14.81,
    dividendYield: 0,
    debtToEquity: 1.15,
    yearsProfitable: 8,
    growthRate: 7,
    aaaYield: AAA_YIELD,
  },
];
