/**
 * Shop Icons — production-grade SVGs for shop items.
 *
 * Generated by יפיופי × מוני × רטנשן (asset library reviewed in
 * `assets-library.html`). Uses `react-native-svg` (already in deps).
 *
 * Pattern: each icon takes optional `size` prop (default 24). Stroke widths
 * and color stops are hand-tuned — don't naïvely scale via `transform`.
 *
 * Lookup helper: `getShopSvgIcon(itemId)` — returns the right component for
 * a shop item id, or `null` if none. Used by ShopItemCard to render SVG
 * before falling back to Lottie.
 */
import React from 'react';
import Svg, {
  Defs,
  LinearGradient,
  RadialGradient,
  Stop,
  Path,
  Circle,
  Rect,
  Ellipse,
  Line,
  G,
  Text as SvgText,
} from 'react-native-svg';

interface IconProps {
  size?: number;
}

// ────────────────────────────────────────────────────────────
// BOOST ICONS · 24×24
// ────────────────────────────────────────────────────────────

export const BoostXP: React.FC<IconProps> = ({ size = 24 }) => (
  <Svg width={size} height={size} viewBox="0 0 24 24">
    <Defs>
      <LinearGradient id="xpG" x1="0" y1="0" x2="0" y2="1">
        <Stop offset="0" stopColor="#a78bfa" />
        <Stop offset="1" stopColor="#7c3aed" />
      </LinearGradient>
    </Defs>
    <Path d="M13 2 L4 14 H10 L9 22 L20 9 H14 Z" fill="url(#xpG)" stroke="#3b1d80" strokeWidth={1} strokeLinejoin="round" />
    <SvgText x={12} y={14} fontSize={6} fontWeight="900" textAnchor="middle" fill="#fbf6e7">XP</SvgText>
  </Svg>
);

export const BoostCoins: React.FC<IconProps> = ({ size = 24 }) => (
  <Svg width={size} height={size} viewBox="0 0 24 24">
    <Defs>
      <RadialGradient id="cnG" cx="40%" cy="35%" r="65%">
        <Stop offset="0" stopColor="#fde68a" />
        <Stop offset="1" stopColor="#facc15" />
      </RadialGradient>
    </Defs>
    <Ellipse cx={9} cy={14} rx={6} ry={6} fill="url(#cnG)" stroke="#854d0e" strokeWidth={1.4} />
    <Ellipse cx={15} cy={10} rx={6} ry={6} fill="url(#cnG)" stroke="#854d0e" strokeWidth={1.4} />
    <Circle cx={19} cy={18} r={4.2} fill="#dc2626" stroke="#7f1d1d" strokeWidth={1} />
    <SvgText x={19} y={20.2} fontSize={5.5} fontWeight="900" textAnchor="middle" fill="#fef9c3">×2</SvgText>
  </Svg>
);

export const BoostMega: React.FC<IconProps> = ({ size = 24 }) => (
  <Svg width={size} height={size} viewBox="0 0 24 24">
    <Defs>
      <LinearGradient id="mgG" x1="0" y1="0" x2="1" y2="1">
        <Stop offset="0" stopColor="#fde047" />
        <Stop offset="0.45" stopColor="#fb923c" />
        <Stop offset="1" stopColor="#dc2626" />
      </LinearGradient>
      <RadialGradient id="mgGlow" cx="50%" cy="45%" r="55%">
        <Stop offset="0" stopColor="#fde047" stopOpacity={0.55} />
        <Stop offset="0.6" stopColor="#fb923c" stopOpacity={0.18} />
        <Stop offset="1" stopColor="#dc2626" stopOpacity={0} />
      </RadialGradient>
    </Defs>
    <Circle cx={12} cy={11} r={11} fill="url(#mgGlow)" />
    <Path d="M12 2 Q16 6 16 14 L14 18 H10 L8 14 Q8 6 12 2 Z" fill="url(#mgG)" stroke="#7f1d1d" strokeWidth={1.2} strokeLinejoin="round" />
    <Circle cx={12} cy={9} r={2} fill="#fef3c7" stroke="#7f1d1d" strokeWidth={1} />
    <Path d="M8 14 L5 17 L7 18 L9 16 Z" fill="#fb923c" stroke="#7f1d1d" strokeWidth={1} strokeLinejoin="round" />
    <Path d="M16 14 L19 17 L17 18 L15 16 Z" fill="#fb923c" stroke="#7f1d1d" strokeWidth={1} strokeLinejoin="round" />
    <Path d="M10 18 Q12 22 14 18 Q13 20 12 19.5 Q11 20 10 18 Z" fill="#fde047" />
    <Path d="M12 2.2 L12.7 3.4 L14 3.5 L13 4.3 L13.3 5.6 L12 5 L10.7 5.6 L11 4.3 L10 3.5 L11.3 3.4 Z" fill="#fef9c3" opacity={0.9} />
  </Svg>
);

export const BoostWeekend: React.FC<IconProps> = ({ size = 24 }) => (
  <Svg width={size} height={size} viewBox="0 0 24 24">
    <Defs>
      <LinearGradient id="wkG" x1="0" y1="0" x2="0" y2="1">
        <Stop offset="0" stopColor="#22d3ee" />
        <Stop offset="1" stopColor="#0891b2" />
      </LinearGradient>
    </Defs>
    <Rect x={3} y={5} width={18} height={16} rx={2.5} fill="url(#wkG)" stroke="#155e75" strokeWidth={1.4} />
    <Rect x={3} y={5} width={18} height={5} fill="#0e7490" />
    <Line x1={7} y1={3} x2={7} y2={8} stroke="#155e75" strokeWidth={1.6} strokeLinecap="round" />
    <Line x1={17} y1={3} x2={17} y2={8} stroke="#155e75" strokeWidth={1.6} strokeLinecap="round" />
    <Path d="M12 11 L13.3 14.3 L17 14.5 L14 16.7 L15.2 20 L12 18 L8.8 20 L10 16.7 L7 14.5 L10.7 14.3 Z" fill="#facc15" stroke="#854d0e" strokeWidth={0.8} strokeLinejoin="round" />
  </Svg>
);

// ────────────────────────────────────────────────────────────
// SHIELD ICONS · 24×24
// ────────────────────────────────────────────────────────────

export const ShieldWeek: React.FC<IconProps> = ({ size = 24 }) => (
  <Svg width={size} height={size} viewBox="0 0 24 24">
    <Path d="M12 2 L20 5 V12 Q20 18 12 22 Q4 18 4 12 V5 Z" fill="#a3e635" stroke="#365314" strokeWidth={1.4} strokeLinejoin="round" />
    <Path d="M12 2 L20 5 V12 Q20 18 12 22" fill="#84cc16" opacity={0.5} />
    <SvgText x={12} y={14} fontSize={6} fontWeight="900" textAnchor="middle" fill="#fbf6e7">7</SvgText>
  </Svg>
);

export const ShieldMonth: React.FC<IconProps> = ({ size = 24 }) => (
  <Svg width={size} height={size} viewBox="0 0 24 24">
    <Path d="M12 2 L20 5 V12 Q20 18 12 22 Q4 18 4 12 V5 Z" fill="#60a5fa" stroke="#1e3a8a" strokeWidth={1.4} strokeLinejoin="round" />
    <Path d="M12 2 L20 5 V12 Q20 18 12 22" fill="#3b82f6" opacity={0.5} />
    <Circle cx={12} cy={6.5} r={1.4} fill="#fbf6e7" />
    <SvgText x={12} y={14} fontSize={6} fontWeight="900" textAnchor="middle" fill="#fbf6e7">30</SvgText>
  </Svg>
);

export const ShieldElite: React.FC<IconProps> = ({ size = 24 }) => (
  <Svg width={size} height={size} viewBox="0 0 24 24">
    <Defs>
      <LinearGradient id="eliteG" x1="0" y1="0" x2="0" y2="1">
        <Stop offset="0" stopColor="#fde68a" />
        <Stop offset="0.5" stopColor="#facc15" />
        <Stop offset="1" stopColor="#b45309" />
      </LinearGradient>
      <RadialGradient id="eliteGlow" cx="50%" cy="50%" r="55%">
        <Stop offset="0" stopColor="#fde047" stopOpacity={0.5} />
        <Stop offset="1" stopColor="#facc15" stopOpacity={0} />
      </RadialGradient>
    </Defs>
    <Circle cx={12} cy={12} r={11} fill="url(#eliteGlow)" />
    <Path d="M12 2 L20 5 V12 Q20 18 12 22 Q4 18 4 12 V5 Z" fill="url(#eliteG)" stroke="#7c2d12" strokeWidth={1.4} strokeLinejoin="round" />
    <Path d="M12 7 Q9 11 9 14 Q9 17 12 18 Q15 17 15 14 Q15 11 12 7 Z" fill="#dc2626" stroke="#7c2d12" strokeWidth={1} strokeLinejoin="round" />
    <Path d="M12 10 Q11 12 11 14 Q11 16 12 16.5 Q13 16 13 14 Q13 12 12 10 Z" fill="#fde047" />
  </Svg>
);

// ────────────────────────────────────────────────────────────
// HEART ICONS · 24×24
// ────────────────────────────────────────────────────────────

export const HeartRefill1: React.FC<IconProps> = ({ size = 24 }) => (
  <Svg width={size} height={size} viewBox="0 0 24 24">
    <Defs>
      <RadialGradient id="hG1" cx="40%" cy="35%" r="65%">
        <Stop offset="0" stopColor="#fca5a5" />
        <Stop offset="1" stopColor="#dc2626" />
      </RadialGradient>
    </Defs>
    <Path d="M12 21 Q3 14 3 8 Q3 3 8 3 Q11 3 12 6 Q13 3 16 3 Q21 3 21 8 Q21 14 12 21 Z" fill="url(#hG1)" stroke="#7f1d1d" strokeWidth={1.4} strokeLinejoin="round" />
    <Circle cx={18} cy={18} r={4} fill="#22c55e" stroke="#14532d" strokeWidth={1} />
    <SvgText x={18} y={20} fontSize={5.5} fontWeight="900" textAnchor="middle" fill="#fef9c3">+1</SvgText>
  </Svg>
);

export const HeartRefillFull: React.FC<IconProps> = ({ size = 24 }) => (
  <Svg width={size} height={size} viewBox="0 0 24 24">
    <Defs>
      <RadialGradient id="hG2" cx="40%" cy="35%" r="65%">
        <Stop offset="0" stopColor="#fecaca" />
        <Stop offset="0.5" stopColor="#ef4444" />
        <Stop offset="1" stopColor="#7f1d1d" />
      </RadialGradient>
      <RadialGradient id="hGlow" cx="50%" cy="50%" r="55%">
        <Stop offset="0" stopColor="#fb7185" stopOpacity={0.5} />
        <Stop offset="1" stopColor="#dc2626" stopOpacity={0} />
      </RadialGradient>
    </Defs>
    <Circle cx={12} cy={12} r={11} fill="url(#hGlow)" />
    <Path d="M6 18 Q1 13 1 9 Q1 6 4 6 Q5 6 6 8 Q7 6 8 6 Q11 6 11 9 Q11 13 6 18 Z" fill="url(#hG2)" stroke="#7f1d1d" strokeWidth={1.1} strokeLinejoin="round" opacity={0.85} />
    <Path d="M18 18 Q13 13 13 9 Q13 6 16 6 Q17 6 18 8 Q19 6 20 6 Q23 6 23 9 Q23 13 18 18 Z" fill="url(#hG2)" stroke="#7f1d1d" strokeWidth={1.1} strokeLinejoin="round" opacity={0.85} />
    <Path d="M12 14 Q5 7 5 4 Q5 1 9 1 Q11 1 12 3 Q13 1 15 1 Q19 1 19 4 Q19 7 12 14 Z" fill="url(#hG2)" stroke="#7f1d1d" strokeWidth={1.3} strokeLinejoin="round" />
  </Svg>
);

// ────────────────────────────────────────────────────────────
// HINT ICONS · 24×24
// ────────────────────────────────────────────────────────────

export const HintSingle: React.FC<IconProps> = ({ size = 24 }) => (
  <Svg width={size} height={size} viewBox="0 0 24 24">
    <Defs>
      <RadialGradient id="bulbG" cx="50%" cy="35%" r="55%">
        <Stop offset="0" stopColor="#fef3c7" />
        <Stop offset="1" stopColor="#facc15" />
      </RadialGradient>
    </Defs>
    <Circle cx={12} cy={9} r={9} fill="#facc15" opacity={0.18} />
    <Path d="M12 2 Q6 2 6 9 Q6 13 9 15 V17 H15 V15 Q18 13 18 9 Q18 2 12 2 Z" fill="url(#bulbG)" stroke="#854d0e" strokeWidth={1.3} strokeLinejoin="round" />
    <Rect x={9} y={17} width={6} height={2.5} rx={0.6} fill="#a16207" stroke="#854d0e" strokeWidth={0.8} />
    <Rect x={10} y={20} width={4} height={2} rx={0.5} fill="#78350f" />
    <Path d="M9 6 Q10 4 13 4" fill="none" stroke="#fef9c3" strokeWidth={1.3} strokeLinecap="round" opacity={0.8} />
  </Svg>
);

export const HintBundle: React.FC<IconProps> = ({ size = 24 }) => (
  <Svg width={size} height={size} viewBox="0 0 24 24">
    <Defs>
      <RadialGradient id="bulbG2" cx="50%" cy="35%" r="55%">
        <Stop offset="0" stopColor="#fef3c7" />
        <Stop offset="1" stopColor="#facc15" />
      </RadialGradient>
    </Defs>
    <G transform="translate(-1 1) scale(0.65)">
      <Path d="M12 2 Q6 2 6 9 Q6 13 9 15 V17 H15 V15 Q18 13 18 9 Q18 2 12 2 Z" fill="url(#bulbG2)" stroke="#854d0e" strokeWidth={1.6} strokeLinejoin="round" />
      <Rect x={9} y={17} width={6} height={2.5} rx={0.6} fill="#a16207" />
    </G>
    <G transform="translate(8 1) scale(0.65)">
      <Path d="M12 2 Q6 2 6 9 Q6 13 9 15 V17 H15 V15 Q18 13 18 9 Q18 2 12 2 Z" fill="url(#bulbG2)" stroke="#854d0e" strokeWidth={1.6} strokeLinejoin="round" />
      <Rect x={9} y={17} width={6} height={2.5} rx={0.6} fill="#a16207" />
    </G>
    <G transform="translate(3 9) scale(0.65)">
      <Path d="M12 2 Q6 2 6 9 Q6 13 9 15 V17 H15 V15 Q18 13 18 9 Q18 2 12 2 Z" fill="url(#bulbG2)" stroke="#854d0e" strokeWidth={1.6} strokeLinejoin="round" />
      <Rect x={9} y={17} width={6} height={2.5} rx={0.6} fill="#a16207" />
    </G>
    <Circle cx={20} cy={20} r={3.6} fill="#dc2626" stroke="#7f1d1d" strokeWidth={1} />
    <SvgText x={20} y={21.8} fontSize={4.5} fontWeight="900" textAnchor="middle" fill="#fef9c3">×5</SvgText>
  </Svg>
);

// ────────────────────────────────────────────────────────────
// FREEZE ICONS · 24×24
// ────────────────────────────────────────────────────────────

export const FreezeSingle: React.FC<IconProps> = ({ size = 24 }) => (
  <Svg width={size} height={size} viewBox="0 0 24 24">
    <Defs>
      <LinearGradient id="frG" x1="0" y1="0" x2="0" y2="1">
        <Stop offset="0" stopColor="#bae6fd" />
        <Stop offset="1" stopColor="#0891b2" />
      </LinearGradient>
    </Defs>
    <G stroke="url(#frG)" strokeWidth={1.6} strokeLinecap="round" fill="none">
      <Line x1={12} y1={3} x2={12} y2={21} />
      <Line x1={3} y1={12} x2={21} y2={12} />
      <Line x1={6} y1={6} x2={18} y2={18} />
      <Line x1={18} y1={6} x2={6} y2={18} />
      <Path d="M12 3 L10 5 M12 3 L14 5" />
      <Path d="M12 21 L10 19 M12 21 L14 19" />
      <Path d="M3 12 L5 10 M3 12 L5 14" />
      <Path d="M21 12 L19 10 M21 12 L19 14" />
    </G>
    <Circle cx={12} cy={12} r={2.5} fill="#0891b2" stroke="#0e7490" strokeWidth={1} />
    <Circle cx={12} cy={12} r={1} fill="#bae6fd" />
  </Svg>
);

export const FreezeBundle: React.FC<IconProps> = ({ size = 24 }) => (
  <Svg width={size} height={size} viewBox="0 0 24 24">
    <Defs>
      <LinearGradient id="frG2" x1="0" y1="0" x2="0" y2="1">
        <Stop offset="0" stopColor="#bae6fd" />
        <Stop offset="1" stopColor="#0891b2" />
      </LinearGradient>
    </Defs>
    <G transform="translate(0 -1) scale(0.55)" opacity={0.75}>
      <G stroke="url(#frG2)" strokeWidth={2.5} strokeLinecap="round" fill="none">
        <Line x1={12} y1={3} x2={12} y2={21} />
        <Line x1={3} y1={12} x2={21} y2={12} />
        <Line x1={6} y1={6} x2={18} y2={18} />
        <Line x1={18} y1={6} x2={6} y2={18} />
      </G>
    </G>
    <G transform="translate(11 1) scale(0.55)" opacity={0.85}>
      <G stroke="url(#frG2)" strokeWidth={2.5} strokeLinecap="round" fill="none">
        <Line x1={12} y1={3} x2={12} y2={21} />
        <Line x1={3} y1={12} x2={21} y2={12} />
        <Line x1={6} y1={6} x2={18} y2={18} />
        <Line x1={18} y1={6} x2={6} y2={18} />
      </G>
    </G>
    <G transform="translate(5 8) scale(0.55)">
      <G stroke="url(#frG2)" strokeWidth={2.6} strokeLinecap="round" fill="none">
        <Line x1={12} y1={3} x2={12} y2={21} />
        <Line x1={3} y1={12} x2={21} y2={12} />
        <Line x1={6} y1={6} x2={18} y2={18} />
        <Line x1={18} y1={6} x2={6} y2={18} />
      </G>
      <Circle cx={12} cy={12} r={3} fill="#0891b2" />
    </G>
  </Svg>
);

// ────────────────────────────────────────────────────────────
// LOOKUP — by ShopItem id
// ────────────────────────────────────────────────────────────

const SHOP_SVG_BY_ID: Record<string, React.FC<IconProps>> = {
  // boosts
  'boost-xp-2x-1h': BoostXP,
  'boost-coins-2x-1h': BoostCoins,
  'boost-mega-1h': BoostMega,
  'boost-weekend': BoostWeekend,
  // shields
  'streak-shield-week': ShieldWeek,
  'streak-shield-month': ShieldMonth,
  'streak-revival-elite': ShieldElite,
  // hearts
  'heart-refill-1': HeartRefill1,
  'heart-refill-full': HeartRefillFull,
  // hints
  'hint-single': HintSingle,
  'hint-bundle': HintBundle,
  // freezes
  'streak-freeze': FreezeSingle,
  'streak-freeze-bundle': FreezeBundle,
};

/**
 * Returns the SVG component for a shop item id, or null if no SVG is available
 * (in which case the caller should fall back to the item's Lottie or emoji).
 */
export function getShopSvgIcon(itemId: string): React.FC<IconProps> | null {
  return SHOP_SVG_BY_ID[itemId] ?? null;
}
